#ifndef GMAX_ICONS_H
#define GMAX_ICONS_H

/*
 * Icon descriptions below were reverse-engineered from gmax-icons-24.png
 * (a 32-column, 24px-per-cell sprite sheet, packed in the same row-major
 * order as this enum) plus knowledge of gmax 1.2 / 3ds max R3-era UI
 * conventions. Confidence varies a lot by group:
 *
 *   - No "?"      : visually confirmed and/or matches one of the
 *                   GMAX_ICON_* aliases at the bottom of this file
 *                   (SELECT, MOVE, ROTATE, SCALE, BOX, SPHERE, CYLINDER,
 *                   CONE, TORUS, PRISM, CAPSULE, POINT_LIGHT, DIR_LIGHT,
 *                   CAMERA, TAPER, TWIST, BEND, STRETCH, SKEW, EXTRUDE,
 *                   MIRROR, NOISE, SHELL, ARRAY, the TAB_* panel icons,
 *                   GRID, FRAME), or a small enough/self-evident group
 *                   (CAMERAS, COMPOUND, CREATETYPES, SPLINES, STANDARD,
 *                   PATCHES, SEPARATOR, TASKPANEL, VPORT_LAYOUT).
 *   - Trailing "?": an educated guess based on typical gmax/max toolbar
 *                   layout and the icon's rough visual appearance, but
 *                   NOT individually verified pixel-by-pixel. This is
 *                   most of CLASSIC_24, MAINTOOLBAR_24, and the very
 *                   dense/repetitive dialog toolbars (MEDITIMAGES,
 *                   MEDITTOOLS, POLYTOOLS_24, SNAPSCONTROLS_24,
 *                   STATUSPANEL_16, SUBOBJECTICONS_24, SVTOOLICONS,
 *                   TIMEPANEL_16, TRACKVIEW*, VIEWCONTROLS_16,
 *                   VIEWPORTNAVIGATIONCONTROLS_24, GAMETOOLS_24,
 *                   DEFORM_MODIFIERS_24, MATERIAL_MODIFIERS_24,
 *                   MAX_EDIT_MODIFIERS_24) where many icons are
 *                   near-identical 24x24 glyphs (paired enabled/disabled
 *                   states, axis-letter variants, etc.) that can't be
 *                   told apart with certainty without gmax's own
 *                   tooltip/string table.
 *
 * Treat "?" entries as a reasonable starting point to check against
 * actual gmax behavior, not ground truth.
 */

enum {
	GMAX_ICON_SIZE = 24,
	GMAX_ICON_COLS = 32,
	GMAX_ICON_SHEET_W = 768,
	GMAX_ICON_SHEET_H = 672,

	GMAX_ICON_CAMERAS_24_000 = 0,  // Target Camera
	GMAX_ICON_CAMERAS_24_001 = 1,  // Free Camera
	GMAX_ICON_CLASSIC_24_000 = 2,  // Classic toolbar: Undo (normal)?
	GMAX_ICON_CLASSIC_24_001 = 3,  // Classic toolbar: Undo (disabled/alt)?
	GMAX_ICON_CLASSIC_24_002 = 4,  // Classic toolbar: Redo (normal)?
	GMAX_ICON_CLASSIC_24_003 = 5,  // Classic toolbar: Redo (disabled/alt)?
	GMAX_ICON_CLASSIC_24_004 = 6,  // Classic toolbar: Select and Link (normal)?
	GMAX_ICON_CLASSIC_24_005 = 7,  // Classic toolbar: Select and Link (disabled/alt)?
	GMAX_ICON_CLASSIC_24_006 = 8,  // Classic toolbar: Unlink Selection (normal)?
	GMAX_ICON_CLASSIC_24_007 = 9,  // Classic toolbar: Unlink Selection (disabled/alt)?
	GMAX_ICON_CLASSIC_24_008 = 10,  // Classic toolbar: Bind to Space Warp (normal)?
	GMAX_ICON_CLASSIC_24_009 = 11,  // Classic toolbar: Bind to Space Warp (disabled/alt)?
	GMAX_ICON_CLASSIC_24_010 = 12,  // Classic toolbar: Select Object (normal)?
	GMAX_ICON_CLASSIC_24_011 = 13,  // Classic toolbar: Select Object (disabled/alt)?
	GMAX_ICON_CLASSIC_24_012 = 14,  // Classic toolbar: Select by Name (normal)?
	GMAX_ICON_CLASSIC_24_013 = 15,  // Classic toolbar: Select by Name (disabled/alt)?
	GMAX_ICON_CLASSIC_24_014 = 16,  // Classic toolbar: Rectangular Selection Region (normal)?
	GMAX_ICON_CLASSIC_24_015 = 17,  // Classic toolbar: Rectangular Selection Region (disabled/alt)?
	GMAX_ICON_CLASSIC_24_016 = 18,  // Classic toolbar: Window/Crossing Selection Toggle (normal)?
	GMAX_ICON_CLASSIC_24_017 = 19,  // Classic toolbar: Window/Crossing Selection Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_018 = 20,  // Classic toolbar: Select and Move (normal)?
	GMAX_ICON_CLASSIC_24_019 = 21,  // Classic toolbar: Select and Move (disabled/alt)?
	GMAX_ICON_CLASSIC_24_020 = 22,  // Classic toolbar: Select and Rotate (normal)?
	GMAX_ICON_CLASSIC_24_021 = 23,  // Classic toolbar: Select and Rotate (disabled/alt)?
	GMAX_ICON_CLASSIC_24_022 = 24,  // Classic toolbar: Select and Uniform Scale (normal)?
	GMAX_ICON_CLASSIC_24_023 = 25,  // Classic toolbar: Select and Uniform Scale (disabled/alt)?
	GMAX_ICON_CLASSIC_24_024 = 26,  // Classic toolbar: Restrict to X (normal)?
	GMAX_ICON_CLASSIC_24_025 = 27,  // Classic toolbar: Restrict to X (disabled/alt)?
	GMAX_ICON_CLASSIC_24_026 = 28,  // Classic toolbar: Restrict to Y (normal)?
	GMAX_ICON_CLASSIC_24_027 = 29,  // Classic toolbar: Restrict to Y (disabled/alt)?
	GMAX_ICON_CLASSIC_24_028 = 30,  // Classic toolbar: Restrict to Z (normal)?
	GMAX_ICON_CLASSIC_24_029 = 31,  // Classic toolbar: Restrict to Z (disabled/alt)?
	GMAX_ICON_CLASSIC_24_030 = 32,  // Classic toolbar: Restrict to XY (normal)?
	GMAX_ICON_CLASSIC_24_031 = 33,  // Classic toolbar: Restrict to XY (disabled/alt)?
	GMAX_ICON_CLASSIC_24_032 = 34,  // Classic toolbar: Restrict to YZ (normal)?
	GMAX_ICON_CLASSIC_24_033 = 35,  // Classic toolbar: Restrict to YZ (disabled/alt)?
	GMAX_ICON_CLASSIC_24_034 = 36,  // Classic toolbar: Restrict to ZX (normal)?
	GMAX_ICON_CLASSIC_24_035 = 37,  // Classic toolbar: Restrict to ZX (disabled/alt)?
	GMAX_ICON_CLASSIC_24_036 = 38,  // Classic toolbar: Snaps Toggle (normal)?
	GMAX_ICON_CLASSIC_24_037 = 39,  // Classic toolbar: Snaps Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_038 = 40,  // Classic toolbar: Angle Snap Toggle (normal)?
	GMAX_ICON_CLASSIC_24_039 = 41,  // Classic toolbar: Angle Snap Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_040 = 42,  // Classic toolbar: Percent Snap Toggle (normal)?
	GMAX_ICON_CLASSIC_24_041 = 43,  // Classic toolbar: Percent Snap Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_042 = 44,  // Classic toolbar: Spinner Snap Toggle (normal)?
	GMAX_ICON_CLASSIC_24_043 = 45,  // Classic toolbar: Spinner Snap Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_044 = 46,  // Classic toolbar: Named Selection Sets (normal)?
	GMAX_ICON_CLASSIC_24_045 = 47,  // Classic toolbar: Named Selection Sets (disabled/alt)?
	GMAX_ICON_CLASSIC_24_046 = 48,  // Classic toolbar: Mirror Selected Objects (normal)?
	GMAX_ICON_CLASSIC_24_047 = 49,  // Classic toolbar: Mirror Selected Objects (disabled/alt)?
	GMAX_ICON_CLASSIC_24_048 = 50,  // Classic toolbar: Align (normal)?
	GMAX_ICON_CLASSIC_24_049 = 51,  // Classic toolbar: Align (disabled/alt)?
	GMAX_ICON_CLASSIC_24_050 = 52,  // Classic toolbar: Layer Manager (normal)?
	GMAX_ICON_CLASSIC_24_051 = 53,  // Classic toolbar: Layer Manager (disabled/alt)?
	GMAX_ICON_CLASSIC_24_052 = 54,  // Classic toolbar: Curve Editor (normal)?
	GMAX_ICON_CLASSIC_24_053 = 55,  // Classic toolbar: Curve Editor (disabled/alt)?
	GMAX_ICON_CLASSIC_24_054 = 56,  // Classic toolbar: Schematic View (normal)?
	GMAX_ICON_CLASSIC_24_055 = 57,  // Classic toolbar: Schematic View (disabled/alt)?
	GMAX_ICON_CLASSIC_24_056 = 58,  // Classic toolbar: Material Editor (normal)?
	GMAX_ICON_CLASSIC_24_057 = 59,  // Classic toolbar: Material Editor (disabled/alt)?
	GMAX_ICON_CLASSIC_24_058 = 60,  // Classic toolbar: Render Scene (normal)?
	GMAX_ICON_CLASSIC_24_059 = 61,  // Classic toolbar: Render Scene (disabled/alt)?
	GMAX_ICON_CLASSIC_24_060 = 62,  // Classic toolbar: Quick Render (normal)?
	GMAX_ICON_CLASSIC_24_061 = 63,  // Classic toolbar: Quick Render (disabled/alt)?
	GMAX_ICON_CLASSIC_24_062 = 64,  // Classic toolbar: Zoom (normal)?
	GMAX_ICON_CLASSIC_24_063 = 65,  // Classic toolbar: Zoom (disabled/alt)?
	GMAX_ICON_CLASSIC_24_064 = 66,  // Classic toolbar: Pan (normal)?
	GMAX_ICON_CLASSIC_24_065 = 67,  // Classic toolbar: Pan (disabled/alt)?
	GMAX_ICON_CLASSIC_24_066 = 68,  // Classic toolbar: Field of View (normal)?
	GMAX_ICON_CLASSIC_24_067 = 69,  // Classic toolbar: Field of View (disabled/alt)?
	GMAX_ICON_CLASSIC_24_068 = 70,  // Classic toolbar: Min/Max Toggle (normal)?
	GMAX_ICON_CLASSIC_24_069 = 71,  // Classic toolbar: Min/Max Toggle (disabled/alt)?
	GMAX_ICON_CLASSIC_24_070 = 72,  // Classic toolbar: Array (normal)?
	GMAX_ICON_CLASSIC_24_071 = 73,  // Classic toolbar: Array (disabled/alt)?
	GMAX_ICON_CLASSIC_24_072 = 74,  // Classic toolbar: Spacing Tool (normal)?
	GMAX_ICON_CLASSIC_24_073 = 75,  // Classic toolbar: Spacing Tool (disabled/alt)?
	GMAX_ICON_CLASSIC_24_074 = 76,  // Classic toolbar: Normal Align (normal)?
	GMAX_ICON_CLASSIC_24_075 = 77,  // Classic toolbar: Normal Align (disabled/alt)?
	GMAX_ICON_CLASSIC_24_076 = 78,  // Classic toolbar: Align Camera (normal)?
	GMAX_ICON_CLASSIC_24_077 = 79,  // Classic toolbar: Align Camera (disabled/alt)?
	GMAX_ICON_COMPOUND_24_000 = 80,  // Morph
	GMAX_ICON_COMPOUND_24_001 = 81,  // Scatter
	GMAX_ICON_COMPOUND_24_002 = 82,  // Conform
	GMAX_ICON_COMPOUND_24_003 = 83,  // Connect
	GMAX_ICON_COMPOUND_24_004 = 84,  // BlobMesh
	GMAX_ICON_COMPOUND_24_005 = 85,  // ShapeMerge
	GMAX_ICON_COMPOUND_24_006 = 86,  // Boolean
	GMAX_ICON_COMPOUND_24_007 = 87,  // Terrain
	GMAX_ICON_CREATETYPES_16_000 = 88,  // Geometry category tab
	GMAX_ICON_CREATETYPES_16_001 = 89,  // Shapes category tab
	GMAX_ICON_CREATETYPES_16_002 = 90,  // Lights category tab
	GMAX_ICON_CREATETYPES_16_003 = 91,  // Cameras category tab
	GMAX_ICON_CREATETYPES_16_004 = 92,  // Helpers category tab
	GMAX_ICON_CREATETYPES_16_005 = 93,  // Space Warps category tab
	GMAX_ICON_CREATETYPES_16_006 = 94,  // Systems category tab
	GMAX_ICON_DEFORM_MODIFIERS_24_000 = 95,  // FFD(Box) space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_001 = 96,  // FFD(Cyl) space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_002 = 97,  // Wave space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_003 = 98,  // Ripple space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_004 = 99,  // Conform space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_005 = 100,  // Bomb space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_006 = 101,  // Displace space warp?
	GMAX_ICON_DEFORM_MODIFIERS_24_007 = 102,  // PatchDeform space warp?
	GMAX_ICON_GAMETOOLS_24_000 = 103,  // Attach UVW / game tool?
	GMAX_ICON_GAMETOOLS_24_001 = 104,  // Bone Tools?
	GMAX_ICON_GAMETOOLS_24_002 = 105,  // Skin modifier launcher?
	GMAX_ICON_GAMETOOLS_24_003 = 106,  // LOD (Level of Detail) utility?
	GMAX_ICON_GAMETOOLS_24_004 = 107,  // Export to game engine?
	GMAX_ICON_GAMETOOLS_24_005 = 108,  // Preview / test in game?
	GMAX_ICON_GAMETOOLS_24_006 = 109,  // Game camera/track tool?
	GMAX_ICON_GMATERIALED_000 = 110,  // Standard material
	GMAX_ICON_GMATERIALED_001 = 111,  // Multi/Sub-Object material
	GMAX_ICON_GMATERIALED_002 = 112,  // Blend material
	GMAX_ICON_GMATERIALED_003 = 113,  // Double Sided material
	GMAX_ICON_GMATERIALED_004 = 114,  // Matte/Shadow material
	GMAX_ICON_GMATERIALED_005 = 115,  // Morpher material
	GMAX_ICON_GMATERIALED_006 = 116,  // Shell Material
	GMAX_ICON_GMATERIALED_007 = 117,  // Shellac material
	GMAX_ICON_GMATERIALED_008 = 118,  // Top/Bottom material
	GMAX_ICON_GMAX_24_000 = 119,  // gmax application icon
	GMAX_ICON_GMAX_24_001 = 120,  // gmax document/scene icon
	GMAX_ICON_GMAX_BUTTONS_000 = 121,  // gmax dialog button (OK)?
	GMAX_ICON_GMAX_BUTTONS_001 = 122,  // gmax dialog button (Cancel)?
	GMAX_ICON_HELPERS_24_000 = 123,  // Dummy helper
	GMAX_ICON_HELPERS_24_001 = 124,  // Point helper
	GMAX_ICON_HELPERS_24_002 = 125,  // Tape Measure helper
	GMAX_ICON_HELPERS_24_003 = 126,  // Grid helper
	GMAX_ICON_HELPERS_24_004 = 127,  // Compass helper
	GMAX_ICON_HELPERS_24_005 = 128,  // Protractor helper?
	GMAX_ICON_LIGHTS_24_000 = 129,  // Target Spotlight
	GMAX_ICON_LIGHTS_24_001 = 130,  // Free Spotlight
	GMAX_ICON_LIGHTS_24_002 = 131,  // Omni (Point) Light
	GMAX_ICON_LIGHTS_24_003 = 132,  // Target Directional Light
	GMAX_ICON_LIGHTS_24_004 = 133,  // Directional Light
	GMAX_ICON_LIGHTS_24_005 = 134,  // Exclude/Include (light) toggle
	GMAX_ICON_LIGHTS_24_006 = 135,  // Light-related dialog button?
	GMAX_ICON_MAINTOOLBAR_24_000 = 136,  // Undo Scene Operation
	GMAX_ICON_MAINTOOLBAR_24_001 = 137,  // Redo Scene Operation
	GMAX_ICON_MAINTOOLBAR_24_002 = 138,  // Select and Link
	GMAX_ICON_MAINTOOLBAR_24_003 = 139,  // Unlink Selection
	GMAX_ICON_MAINTOOLBAR_24_004 = 140,  // Bind to Space Warp
	GMAX_ICON_MAINTOOLBAR_24_005 = 141,  // Selection Filter
	GMAX_ICON_MAINTOOLBAR_24_006 = 142,  // Rectangular Selection Region
	GMAX_ICON_MAINTOOLBAR_24_007 = 143,  // Circular Selection Region
	GMAX_ICON_MAINTOOLBAR_24_008 = 144,  // Fence Selection Region
	GMAX_ICON_MAINTOOLBAR_24_009 = 145,  // Lasso Selection Region
	GMAX_ICON_MAINTOOLBAR_24_010 = 146,  // Select Object
	GMAX_ICON_MAINTOOLBAR_24_011 = 147,  // Select by Name
	GMAX_ICON_MAINTOOLBAR_24_012 = 148,  // Window Selection Toggle
	GMAX_ICON_MAINTOOLBAR_24_013 = 149,  // Crossing Selection Toggle
	GMAX_ICON_MAINTOOLBAR_24_014 = 150,  // Named Selection Sets
	GMAX_ICON_MAINTOOLBAR_24_015 = 151,  // Create Selection Set
	GMAX_ICON_MAINTOOLBAR_24_016 = 152,  // Mirror Selected Objects
	GMAX_ICON_MAINTOOLBAR_24_017 = 153,  // Align
	GMAX_ICON_MAINTOOLBAR_24_018 = 154,  // Snaps Toggle (3D)
	GMAX_ICON_MAINTOOLBAR_24_019 = 155,  // Angle Snap Toggle
	GMAX_ICON_MAINTOOLBAR_24_020 = 156,  // Select and Move
	GMAX_ICON_MAINTOOLBAR_24_021 = 157,  // Select and Move (flyout state)
	GMAX_ICON_MAINTOOLBAR_24_022 = 158,  // Select and Rotate
	GMAX_ICON_MAINTOOLBAR_24_023 = 159,  // Select and Rotate (flyout state)
	GMAX_ICON_MAINTOOLBAR_24_024 = 160,  // Select and Uniform Scale
	GMAX_ICON_MAINTOOLBAR_24_025 = 161,  // Select and Non-Uniform Scale
	GMAX_ICON_MAINTOOLBAR_24_026 = 162,  // Select and Squash
	GMAX_ICON_MAINTOOLBAR_24_027 = 163,  // Reference Coordinate System: View
	GMAX_ICON_MAINTOOLBAR_24_028 = 164,  // Reference Coordinate System: Screen
	GMAX_ICON_MAINTOOLBAR_24_029 = 165,  // Reference Coordinate System: World
	GMAX_ICON_MAINTOOLBAR_24_030 = 166,  // Use Pivot Point Center
	GMAX_ICON_MAINTOOLBAR_24_031 = 167,  // Use Selection Center
	GMAX_ICON_MAINTOOLBAR_24_032 = 168,  // Use Transform Coordinate Center
	GMAX_ICON_MAINTOOLBAR_24_033 = 169,  // Restrict to X
	GMAX_ICON_MAINTOOLBAR_24_034 = 170,  // Restrict to Y
	GMAX_ICON_MAINTOOLBAR_24_035 = 171,  // Restrict to Z
	GMAX_ICON_MAINTOOLBAR_24_036 = 172,  // Restrict to XY Plane
	GMAX_ICON_MAINTOOLBAR_24_037 = 173,  // Restrict to YZ Plane
	GMAX_ICON_MAINTOOLBAR_24_038 = 174,  // Restrict to ZX Plane
	GMAX_ICON_MAINTOOLBAR_24_039 = 175,  // Percent Snap Toggle
	GMAX_ICON_MAINTOOLBAR_24_040 = 176,  // Spinner Snap Toggle
	GMAX_ICON_MAINTOOLBAR_24_041 = 177,  // Array
	GMAX_ICON_MAINTOOLBAR_24_042 = 178,  // Normal Align
	GMAX_ICON_MAINTOOLBAR_24_043 = 179,  // Place Highlight
	GMAX_ICON_MAINTOOLBAR_24_044 = 180,  // Align Camera
	GMAX_ICON_MAINTOOLBAR_24_045 = 181,  // Align to View
	GMAX_ICON_MAINTOOLBAR_24_046 = 182,  // Layer Manager
	GMAX_ICON_MAINTOOLBAR_24_047 = 183,  // Curve Editor (Track View)
	GMAX_ICON_MAINTOOLBAR_24_048 = 184,  // Schematic View
	GMAX_ICON_MAINTOOLBAR_24_049 = 185,  // Material Editor
	GMAX_ICON_MAINTOOLBAR_24_050 = 186,  // Render Scene Dialog
	GMAX_ICON_MAINTOOLBAR_24_051 = 187,  // Quick Render (Production)
	GMAX_ICON_MAINTOOLBAR_24_052 = 188,  // Render Type
	GMAX_ICON_MAINTOOLBAR_24_053 = 189,  // Render Last
	GMAX_ICON_MAINTOOLBAR_24_054 = 190,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_055 = 191,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_056 = 192,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_057 = 193,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_058 = 194,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_059 = 195,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_060 = 196,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_061 = 197,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_062 = 198,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_063 = 199,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_064 = 200,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_065 = 201,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_066 = 202,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_067 = 203,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_068 = 204,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_069 = 205,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_070 = 206,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_071 = 207,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_072 = 208,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_073 = 209,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_074 = 210,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_075 = 211,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_076 = 212,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_077 = 213,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_078 = 214,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_079 = 215,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_080 = 216,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_081 = 217,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_082 = 218,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_083 = 219,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_084 = 220,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_085 = 221,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_086 = 222,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_087 = 223,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_088 = 224,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_089 = 225,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_090 = 226,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_091 = 227,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_092 = 228,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_093 = 229,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_094 = 230,  // Main toolbar button (unidentified)?
	GMAX_ICON_MAINTOOLBAR_24_095 = 231,  // Main toolbar button (unidentified)?
	GMAX_ICON_MATERIAL_MODIFIERS_24_000 = 232,  // Material modifier?
	GMAX_ICON_MATERIAL_MODIFIERS_24_001 = 233,  // Material modifier?
	GMAX_ICON_MATERIAL_MODIFIERS_24_002 = 234,  // Material modifier?
	GMAX_ICON_MATERIAL_MODIFIERS_24_003 = 235,  // Material modifier?
	GMAX_ICON_MATERIAL_MODIFIERS_24_004 = 236,  // Material modifier?
	GMAX_ICON_MATERIAL_MODIFIERS_24_005 = 237,  // Material modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_000 = 238,  // Edit Mesh modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_001 = 239,  // Edit Poly modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_002 = 240,  // Edit Patch modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_003 = 241,  // Edit Spline modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_004 = 242,  // Mesh Select modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_005 = 243,  // Poly Select modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_006 = 244,  // Patch Select modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_007 = 245,  // Spline Select modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_008 = 246,  // Face Extrude modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_009 = 247,  // Normal modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_010 = 248,  // Smooth modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_011 = 249,  // Optimize modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_012 = 250,  // Symmetry modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_013 = 251,  // Delete Mesh modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_014 = 252,  // Cap Holes modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_015 = 253,  // STL Check modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_016 = 254,  // Vertex Weld modifier?
	GMAX_ICON_MAX_EDIT_MODIFIERS_24_017 = 255,  // Edit modifier (other)?
	GMAX_ICON_MAXSCRIPT_24_000 = 256,  // New MAXScript
	GMAX_ICON_MAXSCRIPT_24_001 = 257,  // MAXScript (MS) button
	GMAX_ICON_MAXSCRIPT_24_002 = 258,  // Run MAXScript
	GMAX_ICON_MEDITIMAGES_000 = 259,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_001 = 260,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_002 = 261,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_003 = 262,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_004 = 263,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_005 = 264,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_006 = 265,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_007 = 266,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_008 = 267,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_009 = 268,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_010 = 269,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_011 = 270,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_012 = 271,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_013 = 272,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_014 = 273,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_015 = 274,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_016 = 275,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_017 = 276,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_018 = 277,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_019 = 278,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_020 = 279,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_021 = 280,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_022 = 281,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_023 = 282,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_024 = 283,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_025 = 284,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_026 = 285,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_027 = 286,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_028 = 287,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_029 = 288,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_030 = 289,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_031 = 290,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_032 = 291,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_033 = 292,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_034 = 293,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_035 = 294,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITIMAGES_036 = 295,  // Material Editor sample-slot layout / sample-type icon?
	GMAX_ICON_MEDITTOOLS_000 = 296,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_001 = 297,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_002 = 298,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_003 = 299,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_004 = 300,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_005 = 301,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_006 = 302,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_007 = 303,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_008 = 304,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_009 = 305,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_010 = 306,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_011 = 307,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_012 = 308,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_013 = 309,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_014 = 310,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_015 = 311,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_016 = 312,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_017 = 313,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_018 = 314,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_019 = 315,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_020 = 316,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_021 = 317,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_022 = 318,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_023 = 319,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_024 = 320,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_025 = 321,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_026 = 322,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_027 = 323,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_028 = 324,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_029 = 325,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_030 = 326,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_031 = 327,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_032 = 328,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_033 = 329,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_034 = 330,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_035 = 331,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_036 = 332,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_037 = 333,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_038 = 334,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_039 = 335,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_040 = 336,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_041 = 337,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_MEDITTOOLS_042 = 338,  // Material Editor toolbar tool (Get/Put/Assign/Navigator/etc.)?
	GMAX_ICON_PATCHES_24_000 = 339,  // Quad Patch
	GMAX_ICON_PATCHES_24_001 = 340,  // Tri Patch
	GMAX_ICON_POLYTOOLS_24_000 = 341,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_001 = 342,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_002 = 343,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_003 = 344,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_004 = 345,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_005 = 346,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_006 = 347,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_007 = 348,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_008 = 349,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_009 = 350,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_010 = 351,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_011 = 352,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_012 = 353,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_013 = 354,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_014 = 355,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_POLYTOOLS_24_015 = 356,  // Editable Poly toolbar tool (Extrude/Bevel/Chamfer/Cut/etc.)?
	GMAX_ICON_SEPARATOR_24_000 = 357,  // Toolbar separator
	GMAX_ICON_SEPARATOR_24_001 = 358,  // Toolbar separator
	GMAX_ICON_SHOWICON_24_000 = 359,  // Show End Result toggle (on)
	GMAX_ICON_SHOWICON_24_001 = 360,  // Show End Result toggle (off)
	GMAX_ICON_SHOWICON_24_002 = 361,  // Show sub-object / generic show icon
	GMAX_ICON_SNAPSCONTROLS_24_000 = 362,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_001 = 363,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_002 = 364,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_003 = 365,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_004 = 366,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_005 = 367,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_006 = 368,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_007 = 369,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_008 = 370,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_009 = 371,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_010 = 372,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_011 = 373,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_012 = 374,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_013 = 375,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_014 = 376,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_015 = 377,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_016 = 378,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_017 = 379,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_018 = 380,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_019 = 381,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_020 = 382,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_021 = 383,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_022 = 384,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_023 = 385,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_024 = 386,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_025 = 387,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_026 = 388,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_027 = 389,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_028 = 390,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_029 = 391,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_030 = 392,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SNAPSCONTROLS_24_031 = 393,  // Snap toggle control (2D/2.5D/3D, Angle/Percent/Spinner Snap)?
	GMAX_ICON_SPLINES_24_000 = 394,  // Line
	GMAX_ICON_SPLINES_24_001 = 395,  // Circle
	GMAX_ICON_SPLINES_24_002 = 396,  // Arc
	GMAX_ICON_SPLINES_24_003 = 397,  // NGon
	GMAX_ICON_SPLINES_24_004 = 398,  // Text
	GMAX_ICON_SPLINES_24_005 = 399,  // Star
	GMAX_ICON_SPLINES_24_006 = 400,  // Ellipse
	GMAX_ICON_SPLINES_24_007 = 401,  // Rectangle
	GMAX_ICON_SPLINES_24_008 = 402,  // Donut
	GMAX_ICON_SPLINES_24_009 = 403,  // Helix
	GMAX_ICON_SPLINES_24_010 = 404,  // Section
	GMAX_ICON_STANDARD_24_000 = 405,  // Box
	GMAX_ICON_STANDARD_24_001 = 406,  // Sphere
	GMAX_ICON_STANDARD_24_002 = 407,  // Cylinder
	GMAX_ICON_STANDARD_24_003 = 408,  // Torus
	GMAX_ICON_STANDARD_24_004 = 409,  // Teapot
	GMAX_ICON_STANDARD_24_005 = 410,  // Cone
	GMAX_ICON_STANDARD_24_006 = 411,  // GeoSphere
	GMAX_ICON_STANDARD_24_007 = 412,  // Capsule
	GMAX_ICON_STANDARD_24_008 = 413,  // Prism
	GMAX_ICON_STANDARD_24_009 = 414,  // Plane
	GMAX_ICON_STANDARD_MODIFIERS_24_000 = 415,  // Bend
	GMAX_ICON_STANDARD_MODIFIERS_24_001 = 416,  // Taper
	GMAX_ICON_STANDARD_MODIFIERS_24_002 = 417,  // Skew
	GMAX_ICON_STANDARD_MODIFIERS_24_003 = 418,  // Twist
	GMAX_ICON_STANDARD_MODIFIERS_24_004 = 419,  // Stretch
	GMAX_ICON_STANDARD_MODIFIERS_24_005 = 420,  // Squeeze?
	GMAX_ICON_STANDARD_MODIFIERS_24_006 = 421,  // Noise
	GMAX_ICON_STANDARD_MODIFIERS_24_007 = 422,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_008 = 423,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_009 = 424,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_010 = 425,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_011 = 426,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_012 = 427,  // Extrude
	GMAX_ICON_STANDARD_MODIFIERS_24_013 = 428,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_014 = 429,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_015 = 430,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_016 = 431,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_017 = 432,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_018 = 433,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_019 = 434,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_020 = 435,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_021 = 436,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_022 = 437,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_023 = 438,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_024 = 439,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_025 = 440,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_026 = 441,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_027 = 442,  // Mirror
	GMAX_ICON_STANDARD_MODIFIERS_24_028 = 443,  // Shell
	GMAX_ICON_STANDARD_MODIFIERS_24_029 = 444,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_030 = 445,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_031 = 446,  // Array
	GMAX_ICON_STANDARD_MODIFIERS_24_032 = 447,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_033 = 448,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_034 = 449,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_035 = 450,  // Modifier?
	GMAX_ICON_STANDARD_MODIFIERS_24_036 = 451,  // Modifier?
	GMAX_ICON_STATUSPANEL_16_000 = 452,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_001 = 453,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_002 = 454,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_003 = 455,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_004 = 456,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_005 = 457,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_006 = 458,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_007 = 459,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_008 = 460,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_009 = 461,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_010 = 462,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_011 = 463,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_012 = 464,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_013 = 465,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_014 = 466,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_015 = 467,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_016 = 468,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_017 = 469,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_018 = 470,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_019 = 471,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_020 = 472,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_021 = 473,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_022 = 474,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_023 = 475,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_024 = 476,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_025 = 477,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_026 = 478,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_027 = 479,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_028 = 480,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_029 = 481,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_030 = 482,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_031 = 483,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_032 = 484,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_033 = 485,  // Status bar icon (small, unidentified)?
	GMAX_ICON_STATUSPANEL_16_034 = 486,  // Status bar icon (small, unidentified)?
	GMAX_ICON_SUBOBJECTICONS_24_000 = 487,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_001 = 488,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_002 = 489,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_003 = 490,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_004 = 491,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_005 = 492,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_006 = 493,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_007 = 494,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_008 = 495,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_009 = 496,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_010 = 497,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_011 = 498,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_012 = 499,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_013 = 500,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_014 = 501,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_015 = 502,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_016 = 503,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_017 = 504,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_018 = 505,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_019 = 506,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_020 = 507,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_021 = 508,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_022 = 509,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_023 = 510,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_024 = 511,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_025 = 512,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_026 = 513,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_027 = 514,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_028 = 515,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_029 = 516,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_030 = 517,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_031 = 518,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_032 = 519,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_033 = 520,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_034 = 521,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_035 = 522,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_036 = 523,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SUBOBJECTICONS_24_037 = 524,  // Sub-object level icon (Vertex/Edge/Face/Poly/Element related)?
	GMAX_ICON_SURFACE_TOOLS_24_000 = 525,  // Surface tool (CrossSection?)
	GMAX_ICON_SURFACE_TOOLS_24_001 = 526,  // Surface tool (Surface modifier?)
	GMAX_ICON_SVTOOLICONS_000 = 527,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_001 = 528,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_002 = 529,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_003 = 530,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_004 = 531,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_005 = 532,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_006 = 533,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_007 = 534,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_008 = 535,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_009 = 536,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_010 = 537,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_011 = 538,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_012 = 539,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_013 = 540,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_014 = 541,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_015 = 542,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_016 = 543,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_017 = 544,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_018 = 545,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_019 = 546,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_020 = 547,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_021 = 548,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_022 = 549,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_023 = 550,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_024 = 551,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_025 = 552,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_026 = 553,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_027 = 554,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_028 = 555,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_029 = 556,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_030 = 557,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_031 = 558,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_032 = 559,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_033 = 560,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_034 = 561,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SVTOOLICONS_035 = 562,  // Schematic View toolbar icon (filter/zoom/connect tool)?
	GMAX_ICON_SYSTEMS_24_000 = 563,  // Bones system
	GMAX_ICON_SYSTEMS_24_001 = 564,  // Ring Array system?
	GMAX_ICON_SYSTEMS_24_002 = 565,  // Sunlight/Daylight system?
	GMAX_ICON_TASKPANEL_000 = 566,  // Create command panel tab
	GMAX_ICON_TASKPANEL_001 = 567,  // Modify command panel tab
	GMAX_ICON_TASKPANEL_002 = 568,  // Hierarchy command panel tab
	GMAX_ICON_TASKPANEL_003 = 569,  // Motion command panel tab
	GMAX_ICON_TASKPANEL_004 = 570,  // Display command panel tab
	GMAX_ICON_TASKPANEL_005 = 571,  // Utilities command panel tab
	GMAX_ICON_TIMEPANEL_16_000 = 572,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_001 = 573,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_002 = 574,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_003 = 575,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_004 = 576,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_005 = 577,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_006 = 578,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_007 = 579,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_008 = 580,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_009 = 581,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_010 = 582,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_011 = 583,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_012 = 584,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_013 = 585,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_014 = 586,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_015 = 587,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_016 = 588,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_017 = 589,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_018 = 590,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_019 = 591,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_020 = 592,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_021 = 593,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_022 = 594,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_023 = 595,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_024 = 596,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_025 = 597,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_026 = 598,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TIMEPANEL_16_027 = 599,  // Animation/time playback control icon (VCR-style, small)?
	GMAX_ICON_TRACKVIEWICONS_000 = 600,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_001 = 601,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_002 = 602,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_003 = 603,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_004 = 604,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_005 = 605,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_006 = 606,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_007 = 607,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_008 = 608,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_009 = 609,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_010 = 610,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_011 = 611,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_012 = 612,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_013 = 613,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWICONS_014 = 614,  // Track View key/curve icon (constant/linear/bezier marker)?
	GMAX_ICON_TRACKVIEWSTATUS_000 = 615,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_001 = 616,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_002 = 617,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_003 = 618,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_004 = 619,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_005 = 620,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_006 = 621,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_007 = 622,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_008 = 623,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_009 = 624,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_010 = 625,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_011 = 626,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_012 = 627,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_013 = 628,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_014 = 629,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_015 = 630,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_016 = 631,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_017 = 632,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_018 = 633,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_019 = 634,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_020 = 635,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWSTATUS_021 = 636,  // Track View status bar icon?
	GMAX_ICON_TRACKVIEWTOOLS_000 = 637,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_001 = 638,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_002 = 639,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_003 = 640,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_004 = 641,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_005 = 642,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_006 = 643,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_007 = 644,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_008 = 645,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_009 = 646,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_010 = 647,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_011 = 648,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_012 = 649,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_013 = 650,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_014 = 651,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_015 = 652,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_016 = 653,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_017 = 654,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_018 = 655,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_019 = 656,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_020 = 657,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_021 = 658,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_022 = 659,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_023 = 660,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_024 = 661,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_025 = 662,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_026 = 663,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_027 = 664,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_028 = 665,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_029 = 666,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_030 = 667,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_031 = 668,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_032 = 669,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_033 = 670,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_034 = 671,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_035 = 672,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_036 = 673,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_037 = 674,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_038 = 675,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_039 = 676,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_040 = 677,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_041 = 678,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_042 = 679,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_043 = 680,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_044 = 681,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_045 = 682,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_046 = 683,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_047 = 684,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_048 = 685,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_049 = 686,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_050 = 687,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_051 = 688,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_052 = 689,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_053 = 690,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_054 = 691,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_055 = 692,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_056 = 693,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_057 = 694,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_058 = 695,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_059 = 696,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_060 = 697,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_061 = 698,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_062 = 699,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_063 = 700,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_064 = 701,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_065 = 702,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_066 = 703,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_067 = 704,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_068 = 705,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_069 = 706,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_070 = 707,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_071 = 708,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_072 = 709,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_073 = 710,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_074 = 711,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_075 = 712,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_076 = 713,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_077 = 714,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_078 = 715,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_079 = 716,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_080 = 717,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_081 = 718,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_082 = 719,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_083 = 720,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_084 = 721,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_085 = 722,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_086 = 723,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_087 = 724,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_088 = 725,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_089 = 726,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_090 = 727,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_091 = 728,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_092 = 729,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_093 = 730,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_094 = 731,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_095 = 732,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_096 = 733,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_097 = 734,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_098 = 735,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_099 = 736,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_100 = 737,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_101 = 738,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_102 = 739,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_103 = 740,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_104 = 741,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_105 = 742,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_106 = 743,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_TRACKVIEWTOOLS_107 = 744,  // Track View toolbar tool (filter/edit-keys/edit-time/curve tool)?
	GMAX_ICON_VCRCONTROLS_24_000 = 745,  // Go to Start
	GMAX_ICON_VCRCONTROLS_24_001 = 746,  // Go to Start (pressed)
	GMAX_ICON_VCRCONTROLS_24_002 = 747,  // Previous Frame
	GMAX_ICON_VCRCONTROLS_24_003 = 748,  // Previous Frame (pressed)
	GMAX_ICON_VCRCONTROLS_24_004 = 749,  // Play Animation
	GMAX_ICON_VCRCONTROLS_24_005 = 750,  // Play Animation (pressed)
	GMAX_ICON_VCRCONTROLS_24_006 = 751,  // Next Frame
	GMAX_ICON_VCRCONTROLS_24_007 = 752,  // Next Frame (pressed)
	GMAX_ICON_VCRCONTROLS_24_008 = 753,  // Go to End
	GMAX_ICON_VCRCONTROLS_24_009 = 754,  // Go to End (pressed)
	GMAX_ICON_VCRCONTROLS_24_010 = 755,  // Key Mode Toggle
	GMAX_ICON_VCRCONTROLS_24_011 = 756,  // Key Mode Toggle (pressed)
	GMAX_ICON_VCRCONTROLS_24_012 = 757,  // Set Keys
	GMAX_ICON_VCRCONTROLS_24_013 = 758,  // Set Keys (pressed)
	GMAX_ICON_VCRCONTROLS_24_014 = 759,  // Time Configuration
	GMAX_ICON_VCRCONTROLS_24_015 = 760,  // Time Configuration (pressed)
	GMAX_ICON_VCRCONTROLS_24_016 = 761,  // Auto Key (Animate) Toggle
	GMAX_ICON_VCRCONTROLS_24_017 = 762,  // Auto Key Toggle (pressed)
	GMAX_ICON_VCRCONTROLS_24_018 = 763,  // Play/Stop toggle
	GMAX_ICON_VCRCONTROLS_24_019 = 764,  // Play/Stop toggle (pressed)
	GMAX_ICON_VCRCONTROLS_24_020 = 765,  // Selection lock (time slider)?
	GMAX_ICON_VCRCONTROLS_24_021 = 766,  // Selection lock (pressed)?
	GMAX_ICON_VCRCONTROLS_24_022 = 767,  // New Key?
	GMAX_ICON_VCRCONTROLS_24_023 = 768,  // New Key (pressed)?
	GMAX_ICON_VCRCONTROLS_24_024 = 769,  // Filters?
	GMAX_ICON_VCRCONTROLS_24_025 = 770,  // Filters (pressed)?
	GMAX_ICON_VCRCONTROLS_24_026 = 771,  // VCR control (other)?
	GMAX_ICON_VCRCONTROLS_24_027 = 772,  // VCR control (other, pressed)?
	GMAX_ICON_VIEWCONTROLS_16_000 = 773,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_001 = 774,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_002 = 775,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_003 = 776,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_004 = 777,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_005 = 778,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_006 = 779,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_007 = 780,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_008 = 781,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_009 = 782,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_010 = 783,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_011 = 784,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_012 = 785,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_013 = 786,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_014 = 787,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_015 = 788,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_016 = 789,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_017 = 790,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_018 = 791,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_019 = 792,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_020 = 793,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_021 = 794,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_022 = 795,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_023 = 796,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_024 = 797,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_025 = 798,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_026 = 799,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_027 = 800,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_028 = 801,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_029 = 802,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_030 = 803,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_031 = 804,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_032 = 805,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_033 = 806,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_034 = 807,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_035 = 808,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_036 = 809,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_037 = 810,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_038 = 811,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_039 = 812,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_040 = 813,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_041 = 814,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_042 = 815,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_043 = 816,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_044 = 817,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWCONTROLS_16_045 = 818,  // Viewport navigation control, small (Zoom/Pan/Rotate variant)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_000 = 819,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_001 = 820,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_002 = 821,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_003 = 822,  // Zoom Extents / Frame (all)
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_004 = 823,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_005 = 824,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_006 = 825,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_007 = 826,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_008 = 827,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_009 = 828,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_010 = 829,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_011 = 830,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_012 = 831,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_013 = 832,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_014 = 833,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_015 = 834,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_016 = 835,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_017 = 836,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_018 = 837,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_019 = 838,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_020 = 839,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_021 = 840,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_022 = 841,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_023 = 842,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_024 = 843,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_025 = 844,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_026 = 845,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_027 = 846,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_028 = 847,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_029 = 848,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_030 = 849,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_031 = 850,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_032 = 851,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_033 = 852,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_034 = 853,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_035 = 854,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_036 = 855,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_037 = 856,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_038 = 857,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_039 = 858,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_040 = 859,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_041 = 860,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_042 = 861,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_043 = 862,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_044 = 863,  // Viewport navigation control (24px)?
	GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_045 = 864,  // Viewport navigation control (24px)?
	GMAX_ICON_VPORT_LAYOUT_24_000 = 865,  // Single viewport layout
	GMAX_ICON_VPORT_LAYOUT_24_001 = 866,  // 2 viewports (vertical split)
	GMAX_ICON_VPORT_LAYOUT_24_002 = 867,  // 2 viewports (horizontal split)
	GMAX_ICON_VPORT_LAYOUT_24_003 = 868,  // 3 viewports (1 large + 2 small, right)
	GMAX_ICON_VPORT_LAYOUT_24_004 = 869,  // 3 viewports (1 large + 2 small, left)
	GMAX_ICON_VPORT_LAYOUT_24_005 = 870,  // 3 viewports (1 large top + 2 bottom)
	GMAX_ICON_VPORT_LAYOUT_24_006 = 871,  // 3 viewports (1 large bottom + 2 top)
	GMAX_ICON_VPORT_LAYOUT_24_007 = 872,  // 4 viewports (even grid)
	GMAX_ICON_VPORT_LAYOUT_24_008 = 873,  // 4 viewports (1 large + 3 small, right column)
	GMAX_ICON_VPORT_LAYOUT_24_009 = 874,  // 4 viewports (1 large + 3 small, left column)
	GMAX_ICON_VPORT_LAYOUT_24_010 = 875,  // 4 viewports (1 large top + 3 bottom)
	GMAX_ICON_VPORT_LAYOUT_24_011 = 876,  // 4 viewports (1 large bottom + 3 top)
	GMAX_ICON_VPORT_LAYOUT_24_012 = 877,  // Layout preset (other)
	GMAX_ICON_VPORT_LAYOUT_24_013 = 878,  // Layout preset (other)
	GMAX_ICON_COUNT = 879,

	GMAX_ICON_SELECT = GMAX_ICON_MAINTOOLBAR_24_010,
	GMAX_ICON_MOVE = GMAX_ICON_MAINTOOLBAR_24_020,
	GMAX_ICON_ROTATE = GMAX_ICON_MAINTOOLBAR_24_022,
	GMAX_ICON_SCALE = GMAX_ICON_MAINTOOLBAR_24_024,
	GMAX_ICON_BOX = GMAX_ICON_STANDARD_24_000,
	GMAX_ICON_SPHERE = GMAX_ICON_STANDARD_24_001,
	GMAX_ICON_CYLINDER = GMAX_ICON_STANDARD_24_002,
	GMAX_ICON_CONE = GMAX_ICON_STANDARD_24_005,
	GMAX_ICON_TORUS = GMAX_ICON_STANDARD_24_003,
	GMAX_ICON_PRISM = GMAX_ICON_STANDARD_24_008,
	GMAX_ICON_CAPSULE = GMAX_ICON_STANDARD_24_007,
	GMAX_ICON_ARCH = GMAX_ICON_STANDARD_24_000,
	GMAX_ICON_POINT_LIGHT = GMAX_ICON_LIGHTS_24_002,
	GMAX_ICON_DIR_LIGHT = GMAX_ICON_LIGHTS_24_004,
	GMAX_ICON_CAMERA = GMAX_ICON_CAMERAS_24_000,
	GMAX_ICON_TAPER = GMAX_ICON_STANDARD_MODIFIERS_24_001,
	GMAX_ICON_TWIST = GMAX_ICON_STANDARD_MODIFIERS_24_003,
	GMAX_ICON_BEND = GMAX_ICON_STANDARD_MODIFIERS_24_000,
	GMAX_ICON_STRETCH = GMAX_ICON_STANDARD_MODIFIERS_24_004,
	GMAX_ICON_SKEW = GMAX_ICON_STANDARD_MODIFIERS_24_002,
	GMAX_ICON_EXTRUDE = GMAX_ICON_STANDARD_MODIFIERS_24_012,
	GMAX_ICON_MIRROR = GMAX_ICON_STANDARD_MODIFIERS_24_027,
	GMAX_ICON_NOISE = GMAX_ICON_STANDARD_MODIFIERS_24_006,
	GMAX_ICON_SHELL = GMAX_ICON_STANDARD_MODIFIERS_24_028,
	GMAX_ICON_ARRAY = GMAX_ICON_STANDARD_MODIFIERS_24_031,
	GMAX_ICON_TAB_CREATE = GMAX_ICON_TASKPANEL_000,
	GMAX_ICON_TAB_MODIFY = GMAX_ICON_TASKPANEL_001,
	GMAX_ICON_TAB_HIERARCHY = GMAX_ICON_TASKPANEL_002,
	GMAX_ICON_TAB_MOTION = GMAX_ICON_TASKPANEL_003,
	GMAX_ICON_TAB_DISPLAY = GMAX_ICON_TASKPANEL_004,
	GMAX_ICON_TAB_UTILITIES = GMAX_ICON_TASKPANEL_005,
	GMAX_ICON_GRID = GMAX_ICON_HELPERS_24_003,
	GMAX_ICON_FRAME = GMAX_ICON_VIEWPORTNAVIGATIONCONTROLS_24_003,

	GMAX_ICON_CAMERA_FREE       = GMAX_ICON_CAMERAS_24_001,
	GMAX_ICON_COMPOUND_MORPH    = GMAX_ICON_COMPOUND_24_000,
	GMAX_ICON_COMPOUND_SCATTER  = GMAX_ICON_COMPOUND_24_001,
	GMAX_ICON_COMPOUND_CONFORM  = GMAX_ICON_COMPOUND_24_002,
	GMAX_ICON_COMPOUND_CONNECT  = GMAX_ICON_COMPOUND_24_003,
	GMAX_ICON_COMPOUND_BLOBMESH = GMAX_ICON_COMPOUND_24_004,
	GMAX_ICON_COMPOUND_SHAPEMERGE = GMAX_ICON_COMPOUND_24_005,
	GMAX_ICON_COMPOUND_BOOLEAN  = GMAX_ICON_COMPOUND_24_006,
	GMAX_ICON_COMPOUND_TERRAIN  = GMAX_ICON_COMPOUND_24_007,
	GMAX_ICON_CATEGORY_GEOMETRY    = GMAX_ICON_CREATETYPES_16_000,
	GMAX_ICON_CATEGORY_SHAPES      = GMAX_ICON_CREATETYPES_16_001,
	GMAX_ICON_CATEGORY_LIGHTS      = GMAX_ICON_CREATETYPES_16_002,
	GMAX_ICON_CATEGORY_CAMERAS     = GMAX_ICON_CREATETYPES_16_003,
	GMAX_ICON_CATEGORY_HELPERS     = GMAX_ICON_CREATETYPES_16_004,
	GMAX_ICON_CATEGORY_SPACEWARPS  = GMAX_ICON_CREATETYPES_16_005,
	GMAX_ICON_CATEGORY_SYSTEMS     = GMAX_ICON_CREATETYPES_16_006,
	GMAX_ICON_DEFORM_FFD_BOX    = GMAX_ICON_DEFORM_MODIFIERS_24_000,
	GMAX_ICON_DEFORM_FFD_CYL    = GMAX_ICON_DEFORM_MODIFIERS_24_001,
	GMAX_ICON_DEFORM_WAVE       = GMAX_ICON_DEFORM_MODIFIERS_24_002,
	GMAX_ICON_DEFORM_RIPPLE     = GMAX_ICON_DEFORM_MODIFIERS_24_003,
	GMAX_ICON_DEFORM_CONFORM    = GMAX_ICON_DEFORM_MODIFIERS_24_004,
	GMAX_ICON_DEFORM_BOMB       = GMAX_ICON_DEFORM_MODIFIERS_24_005,
	GMAX_ICON_DEFORM_DISPLACE   = GMAX_ICON_DEFORM_MODIFIERS_24_006,
	GMAX_ICON_DEFORM_PATCHDEFORM = GMAX_ICON_DEFORM_MODIFIERS_24_007,
	GMAX_ICON_HELPER_DUMMY      = GMAX_ICON_HELPERS_24_000,
	GMAX_ICON_HELPER_POINT      = GMAX_ICON_HELPERS_24_001,
	GMAX_ICON_HELPER_TAPE       = GMAX_ICON_HELPERS_24_002,
	GMAX_ICON_HELPER_COMPASS    = GMAX_ICON_HELPERS_24_004,
	GMAX_ICON_HELPER_PROTRACTOR = GMAX_ICON_HELPERS_24_005,
	GMAX_ICON_LIGHT_TARGET_SPOT = GMAX_ICON_LIGHTS_24_000,
	GMAX_ICON_LIGHT_FREE_SPOT   = GMAX_ICON_LIGHTS_24_001,
	GMAX_ICON_LIGHT_OMNI        = GMAX_ICON_LIGHTS_24_002,
	GMAX_ICON_LIGHT_TARGET_DIR  = GMAX_ICON_LIGHTS_24_003,
	GMAX_ICON_LIGHT_DIR         = GMAX_ICON_LIGHTS_24_004,
	GMAX_ICON_LIGHT_EXCLUDE     = GMAX_ICON_LIGHTS_24_005,
	GMAX_ICON_MATERIAL_STANDARD   = GMAX_ICON_GMATERIALED_000,
	GMAX_ICON_MATERIAL_MULTISUB   = GMAX_ICON_GMATERIALED_001,
	GMAX_ICON_MATERIAL_BLEND      = GMAX_ICON_GMATERIALED_002,
	GMAX_ICON_MATERIAL_DOUBLESIDED = GMAX_ICON_GMATERIALED_003,
	GMAX_ICON_MATERIAL_MATTE      = GMAX_ICON_GMATERIALED_004,
	GMAX_ICON_MATERIAL_MORPHER    = GMAX_ICON_GMATERIALED_005,
	GMAX_ICON_MATERIAL_SHELL      = GMAX_ICON_GMATERIALED_006,
	GMAX_ICON_MATERIAL_SHELLAC    = GMAX_ICON_GMATERIALED_007,
	GMAX_ICON_MATERIAL_TOPBOTTOM  = GMAX_ICON_GMATERIALED_008,
	GMAX_ICON_MAXSCRIPT_NEW    = GMAX_ICON_MAXSCRIPT_24_000,
	GMAX_ICON_MAXSCRIPT_OPEN   = GMAX_ICON_MAXSCRIPT_24_001,
	GMAX_ICON_MAXSCRIPT_RUN    = GMAX_ICON_MAXSCRIPT_24_002,
	GMAX_ICON_PATCH_QUAD       = GMAX_ICON_PATCHES_24_000,
	GMAX_ICON_PATCH_TRI        = GMAX_ICON_PATCHES_24_001,
	GMAX_ICON_SPLINE_LINE      = GMAX_ICON_SPLINES_24_000,
	GMAX_ICON_SPLINE_CIRCLE    = GMAX_ICON_SPLINES_24_001,
	GMAX_ICON_SPLINE_ARC       = GMAX_ICON_SPLINES_24_002,
	GMAX_ICON_SPLINE_NGON      = GMAX_ICON_SPLINES_24_003,
	GMAX_ICON_SPLINE_TEXT      = GMAX_ICON_SPLINES_24_004,
	GMAX_ICON_SPLINE_STAR      = GMAX_ICON_SPLINES_24_005,
	GMAX_ICON_SPLINE_ELLIPSE   = GMAX_ICON_SPLINES_24_006,
	GMAX_ICON_SPLINE_RECTANGLE = GMAX_ICON_SPLINES_24_007,
	GMAX_ICON_SPLINE_DONUT     = GMAX_ICON_SPLINES_24_008,
	GMAX_ICON_SPLINE_HELIX     = GMAX_ICON_SPLINES_24_009,
	GMAX_ICON_SPLINE_SECTION   = GMAX_ICON_SPLINES_24_010,
	GMAX_ICON_TEAPOT           = GMAX_ICON_STANDARD_24_004,
	GMAX_ICON_GEOSPHERE        = GMAX_ICON_STANDARD_24_006,
	GMAX_ICON_PLANE            = GMAX_ICON_STANDARD_24_009,
	GMAX_ICON_MOD_SQUEEZE      = GMAX_ICON_STANDARD_MODIFIERS_24_005,
	GMAX_ICON_SURFACE_CROSSSECTION = GMAX_ICON_SURFACE_TOOLS_24_000,
	GMAX_ICON_SURFACE_MODIFIER    = GMAX_ICON_SURFACE_TOOLS_24_001,
	GMAX_ICON_SYSTEM_BONES        = GMAX_ICON_SYSTEMS_24_000,
	GMAX_ICON_SYSTEM_RINGARRAY    = GMAX_ICON_SYSTEMS_24_001,
	GMAX_ICON_SYSTEM_SUNLIGHT     = GMAX_ICON_SYSTEMS_24_002,
	GMAX_ICON_SHOW_ENDRESULT_ON  = GMAX_ICON_SHOWICON_24_000,
	GMAX_ICON_SHOW_ENDRESULT_OFF = GMAX_ICON_SHOWICON_24_001,
	GMAX_ICON_VCR_GOTO_START     = GMAX_ICON_VCRCONTROLS_24_000,
	GMAX_ICON_VCR_PREV_FRAME     = GMAX_ICON_VCRCONTROLS_24_002,
	GMAX_ICON_VCR_PLAY           = GMAX_ICON_VCRCONTROLS_24_004,
	GMAX_ICON_VCR_NEXT_FRAME     = GMAX_ICON_VCRCONTROLS_24_006,
	GMAX_ICON_VCR_GOTO_END       = GMAX_ICON_VCRCONTROLS_24_008,
	GMAX_ICON_VCR_KEY_MODE       = GMAX_ICON_VCRCONTROLS_24_010,
	GMAX_ICON_VCR_SET_KEYS       = GMAX_ICON_VCRCONTROLS_24_012,
	GMAX_ICON_VCR_TIME_CONFIG    = GMAX_ICON_VCRCONTROLS_24_014,
	GMAX_ICON_VCR_AUTO_KEY       = GMAX_ICON_VCRCONTROLS_24_016,
	GMAX_ICON_VCR_PLAY_STOP      = GMAX_ICON_VCRCONTROLS_24_018,
	GMAX_ICON_VPORT_SINGLE       = GMAX_ICON_VPORT_LAYOUT_24_000,
	GMAX_ICON_VPORT_SPLIT_V      = GMAX_ICON_VPORT_LAYOUT_24_001,
	GMAX_ICON_VPORT_SPLIT_H      = GMAX_ICON_VPORT_LAYOUT_24_002,
	GMAX_ICON_VPORT_3_RIGHT      = GMAX_ICON_VPORT_LAYOUT_24_003,
	GMAX_ICON_VPORT_3_LEFT       = GMAX_ICON_VPORT_LAYOUT_24_004,
	GMAX_ICON_VPORT_3_TOP        = GMAX_ICON_VPORT_LAYOUT_24_005,
	GMAX_ICON_VPORT_3_BOTTOM     = GMAX_ICON_VPORT_LAYOUT_24_006,
	GMAX_ICON_VPORT_QUAD         = GMAX_ICON_VPORT_LAYOUT_24_007,
	GMAX_ICON_VPORT_4_RIGHT      = GMAX_ICON_VPORT_LAYOUT_24_008,
	GMAX_ICON_VPORT_4_LEFT       = GMAX_ICON_VPORT_LAYOUT_24_009,
	GMAX_ICON_VPORT_4_TOP        = GMAX_ICON_VPORT_LAYOUT_24_010,
	GMAX_ICON_VPORT_4_BOTTOM     = GMAX_ICON_VPORT_LAYOUT_24_011,
	GMAX_ICON_UNDO              = GMAX_ICON_CLASSIC_24_000,
	GMAX_ICON_REDO              = GMAX_ICON_CLASSIC_24_002,
	GMAX_ICON_LINK              = GMAX_ICON_CLASSIC_24_004,
	GMAX_ICON_UNLINK            = GMAX_ICON_CLASSIC_24_006,
	GMAX_ICON_BIND_WARP        = GMAX_ICON_CLASSIC_24_008,
	GMAX_ICON_SELECT_OBJECT    = GMAX_ICON_CLASSIC_24_010,
	GMAX_ICON_SELECT_BY_NAME   = GMAX_ICON_CLASSIC_24_012,
	GMAX_ICON_SELECT_RECT      = GMAX_ICON_CLASSIC_24_014,
	GMAX_ICON_WINDOW_CROSSING  = GMAX_ICON_CLASSIC_24_016,
	GMAX_ICON_AXIS_X           = GMAX_ICON_CLASSIC_24_024,
	GMAX_ICON_AXIS_Y           = GMAX_ICON_CLASSIC_24_026,
	GMAX_ICON_AXIS_Z           = GMAX_ICON_CLASSIC_24_028,
	GMAX_ICON_AXIS_XY          = GMAX_ICON_CLASSIC_24_030,
	GMAX_ICON_AXIS_YZ          = GMAX_ICON_CLASSIC_24_032,
	GMAX_ICON_AXIS_ZX          = GMAX_ICON_CLASSIC_24_034,
	GMAX_ICON_SNAP_TOGGLE      = GMAX_ICON_CLASSIC_24_036,
	GMAX_ICON_ANGLE_SNAP       = GMAX_ICON_CLASSIC_24_038,
	GMAX_ICON_NAMED_SELSETS    = GMAX_ICON_CLASSIC_24_044,
	GMAX_ICON_ALIGN            = GMAX_ICON_CLASSIC_24_048,
	GMAX_ICON_LAYER_MANAGER    = GMAX_ICON_CLASSIC_24_050,
	GMAX_ICON_CURVE_EDITOR     = GMAX_ICON_CLASSIC_24_052,
	GMAX_ICON_SCHEMATIC_VIEW   = GMAX_ICON_CLASSIC_24_054,
	GMAX_ICON_MATERIAL_EDITOR  = GMAX_ICON_CLASSIC_24_056,
	GMAX_ICON_RENDER_SCENE     = GMAX_ICON_CLASSIC_24_058,
	GMAX_ICON_QUICK_RENDER     = GMAX_ICON_CLASSIC_24_060,
	GMAX_ICON_ZOOM             = GMAX_ICON_CLASSIC_24_062,
	GMAX_ICON_PAN              = GMAX_ICON_CLASSIC_24_064,
	GMAX_ICON_FOV              = GMAX_ICON_CLASSIC_24_066,
	GMAX_ICON_MINMAX_TOGGLE    = GMAX_ICON_CLASSIC_24_068,
	GMAX_ICON_SPACING_TOOL     = GMAX_ICON_CLASSIC_24_072,
	GMAX_ICON_NORMAL_ALIGN     = GMAX_ICON_CLASSIC_24_074,
	GMAX_ICON_ALIGN_CAMERA     = GMAX_ICON_CLASSIC_24_076,
};

#endif