//  test_db_dialog_standalone.c
// Headless test of database-driven dialog infrastructure (Phase 2).
// Exercises the DDX/database plumbing without opening a real modal UI.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ui.h"
#include "test_framework.h"
#include "test_env.h"

// Minimal test schema matching socialfeed authors table
typedef struct {
    int id;
    char name[64];
    char avatar[256];
} test_author_t;

// Minimal generated-style table id for testing
enum { ID_DB_AUTHORS = 0 };

enum {
    ID_TEST_AUTHORS_ID = 1,
    ID_TEST_AUTHORS_NAME = 2,
    ID_TEST_AUTHORS_AVATAR = 3,
};

// Field metadata (would be generated by orionc)
static const db_field_meta_t test_author_fields[] = {
    { ID_TEST_AUTHORS_ID, "id", DB_TYPE_INT, offsetof(test_author_t, id), 0 },
    { ID_TEST_AUTHORS_NAME, "name", DB_TYPE_STRING, offsetof(test_author_t, name), 64 },
    { ID_TEST_AUTHORS_AVATAR, "avatar", DB_TYPE_STRING, offsetof(test_author_t, avatar), 256 },
};

// Minimal in-memory database for testing
typedef struct {
    test_author_t authors[10];
    int author_count;
} test_db_context_t;

// Minimal database proc for testing
static lresult_t test_db_proc(database_t *db, uint32_t msg,
                               uint32_t wparam, void *lparam) {
    test_db_context_t *ctx = (test_db_context_t *)db->userdata;
    
    switch (msg) {
        case dbCreate:
            ctx = calloc(1, sizeof(test_db_context_t));
            db->userdata = ctx;
            // Add one test author
            ctx->authors[0] = (test_author_t){ .id = 1, .name = "Alice", .avatar = "alice.png" };
            ctx->author_count = 1;
            printf("[test_db] Created database with 1 author\n");
            return 1;
            
        case dbDestroy:
            free(ctx);
            return 1;
            
        case dbFind: {
            int table_id = LOWORD(wparam);
            int author_id = (int)(intptr_t)lparam;
            if (table_id == ID_DB_AUTHORS && author_id > 0 && author_id <= ctx->author_count) {
                printf("[test_db] Found author ID %d: %s\n", author_id, ctx->authors[author_id - 1].name);
                return (lresult_t)&ctx->authors[author_id - 1];
            }
            return 0;
        }
            
        case dbInsert: {
            int table_id = wparam;
            if (table_id == ID_DB_AUTHORS && ctx->author_count < 10) {
                test_author_t *new_author = (test_author_t *)lparam;
                new_author->id = ctx->author_count + 1;
                ctx->authors[ctx->author_count] = *new_author;
                ctx->author_count++;
                printf("[test_db] Inserted author ID %d: %s\n",
                       new_author->id, new_author->name);
                return (lresult_t)&ctx->authors[ctx->author_count - 1];
            }
            return 0;
        }
            
        case dbUpdate: {
            int table_id = LOWORD(wparam);
            int author_id = HIWORD(wparam);
            if (table_id == ID_DB_AUTHORS && author_id > 0 && author_id <= ctx->author_count) {
                test_author_t *updated = (test_author_t *)lparam;
                ctx->authors[author_id - 1] = *updated;
                printf("[test_db] Updated author ID %d: %s\n", author_id, updated->name);
                return 1;
            }
            return 0;
        }
            
        default:
            return 0;
    }
}

// Manual form definition for testing (would be generated by orionc)
static const ctrl_binding_t author_bindings[] = {
    DDX_TEXT(1, test_author_t, name),
    DDX_TEXT(2, test_author_t, avatar),
};

static const form_ctrl_def_t author_form_children[] = {
    { .class_name = "StackView", .id = 0, .size = {0, 0}, .flags = WINDOW_FLEXSPACE, .name = "main_stack", .layout_spacing = 8, .padding = {8,8,8,8}, .children = (const form_ctrl_def_t[]){
        { .class_name = "Label", .id = 0, .size = {0, 13}, .text = "Name:", .name = "lbl_name" },
        { .class_name = "TextBox", .id = 1, .size = {0, 13}, .flags = WINDOW_FLEXSPACE, .name = "edit_name" },
        { .class_name = "Label", .id = 0, .size = {0, 13}, .text = "Avatar:", .name = "lbl_avatar" },
        { .class_name = "TextBox", .id = 2, .size = {0, 13}, .flags = WINDOW_FLEXSPACE, .name = "edit_avatar" },
        { .class_name = "Separator", .id = 0, .size = {0, 1}, .name = "sep" },
        { .class_name = "StackView", .id = 0, .size = {0, 19}, .flags = WINDOW_STACK_HORIZONTAL, .layout_spacing = 6, .name = "buttons", .children = (const form_ctrl_def_t[]){
            { .class_name = "Space", .id = 0, .size = {0, 0}, .flags = WINDOW_FLEXSPACE, .name = "spacer" },
            { .class_name = "Button", .id = 100, .size = {60, 19}, .flags = BUTTON_DEFAULT, .text = "OK", .name = "ok" },
            { .class_name = "Button", .id = 101, .size = {60, 19}, .text = "Cancel", .name = "cancel" },
        }, .child_count = 3 },
    }, .child_count = 6 },
};

static const form_def_t author_form = {
    .name = "Edit Author",
    .width = 300,
    .height = 150,
    .flags = WINDOW_AUTO_LAYOUT,
    .children = author_form_children,
    .child_count = 1,
    .bindings = author_bindings,
    .binding_count = 2,
    .ok_id = 100,
    .cancel_id = 101,
    .db_name = "db",
    .db_table = "authors",
    .db_table_id = ID_DB_AUTHORS,
    .db_fields = (const void *)test_author_fields,
    .db_field_count = 3,
};

static lresult_t nop_proc(window_t *win, uint32_t msg, uint32_t wparam, void *lparam) {
    (void)win;
    (void)msg;
    (void)wparam;
    (void)lparam;
    return false;
}

static database_t *create_test_database(void) {
    database_t *db = calloc(1, sizeof(database_t));
    if (!db)
        return NULL;
    db->name = "db";
    db->proc = test_db_proc;
    if (!send_db_message(db, dbCreate, 0, NULL)) {
        free(db);
        return NULL;
    }
    if (!register_database("db", db)) {
        send_db_message(db, dbDestroy, 0, NULL);
        free(db);
        return NULL;
    }
    ui_set_database(db);
    return db;
}

static void destroy_test_database(database_t *db) {
    if (!db)
        return;
    send_db_message(db, dbDestroy, 0, NULL);
    free(db);
    ui_set_database(NULL);
}

void test_db_dialog_metadata_is_self_contained(void) {
    TEST("database dialog form: generated metadata is self-contained");

    ASSERT_STR_EQUAL(author_form.db_name, "db");
    ASSERT_STR_EQUAL(author_form.db_table, "authors");
    ASSERT_EQUAL((int)author_form.db_table_id, ID_DB_AUTHORS);
    ASSERT_NOT_NULL((void *)author_form.db_fields);
    ASSERT_EQUAL(author_form.db_field_count, 3);
    ASSERT_NOT_NULL((void *)author_form.bindings);
    ASSERT_EQUAL(author_form.binding_count, 2);

    PASS();
}

void test_db_dialog_update_existing_record_headless(void) {
    TEST("database dialog plumbing: fetch, DDX pull, update existing record");

    test_env_init();
    database_t *db = create_test_database();
    ASSERT_NOT_NULL(db);

    lresult_t found = send_db_message(db, dbFind,
                                      MAKEDWORD(author_form.db_table_id, 0),
                                      (void *)(intptr_t)1);
    ASSERT_NOT_NULL((void *)found);

    test_author_t record = {0};
    memcpy(&record, (void *)found, sizeof(record));

    window_t *dlg = create_window_from_form(&author_form, 0, 0, NULL,
                                            nop_proc, 0, NULL);
    ASSERT_NOT_NULL(dlg);
    dialog_push(dlg, &record, author_form.bindings, author_form.binding_count);

    window_t *name = get_window_item(dlg, 1);
    ASSERT_NOT_NULL(name);
    send_message(name, edSetText, 0, "Alicia");

    dialog_pull(dlg, &record, author_form.bindings, author_form.binding_count);
    ASSERT_STR_EQUAL(record.name, "Alicia");
    ASSERT_TRUE(send_db_message(db, dbUpdate,
                                MAKEDWORD(author_form.db_table_id, 1),
                                &record));

    test_db_context_t *ctx = (test_db_context_t *)db->userdata;
    ASSERT_STR_EQUAL(ctx->authors[0].name, "Alicia");

    destroy_window(dlg);
    destroy_test_database(db);
    test_env_shutdown();
    PASS();
}

void test_db_dialog_insert_new_record_headless(void) {
    TEST("database dialog plumbing: DDX pull and insert new record");

    test_env_init();
    database_t *db = create_test_database();
    ASSERT_NOT_NULL(db);

    test_author_t record = {0};
    window_t *dlg = create_window_from_form(&author_form, 0, 0, NULL,
                                            nop_proc, 0, NULL);
    ASSERT_NOT_NULL(dlg);

    window_t *name = get_window_item(dlg, 1);
    window_t *avatar = get_window_item(dlg, 2);
    ASSERT_NOT_NULL(name);
    ASSERT_NOT_NULL(avatar);
    send_message(name, edSetText, 0, "Bob");
    send_message(avatar, edSetText, 0, "bob.png");

    dialog_pull(dlg, &record, author_form.bindings, author_form.binding_count);
    test_author_t *inserted = (test_author_t *)send_db_message(db, dbInsert,
                                                               author_form.db_table_id,
                                                               &record);
    ASSERT_NOT_NULL(inserted);
    ASSERT_EQUAL(inserted->id, 2);
    ASSERT_STR_EQUAL(inserted->name, "Bob");
    ASSERT_STR_EQUAL(inserted->avatar, "bob.png");

    test_db_context_t *ctx = (test_db_context_t *)db->userdata;
    ASSERT_EQUAL(ctx->author_count, 2);

    destroy_window(dlg);
    destroy_test_database(db);
    test_env_shutdown();
    PASS();
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;

    TEST_START("Database Dialog Infrastructure");
    test_db_dialog_metadata_is_self_contained();
    test_db_dialog_update_existing_record_headless();
    test_db_dialog_insert_new_record_headless();
    TEST_END();
}
