// socialfeed_db.c — Minimal database-driven social feed
//
// Demonstrates the Zero Wrapper Structs database API with minimal C code.
// Most UI is declared in socialfeed.orion and generated by orionc.

#include "../../ui.h"
#include "../../gem_magic.h"
#include "socialfeed.h"

#ifndef SHAREDIR
#define SHAREDIR "."
#endif

// ══════════════════════════════════════════════════════════════════════════
// Global State (minimal)
// ══════════════════════════════════════════════════════════════════════════

static database_t *g_db = NULL;
static window_t *g_main_win = NULL;
static window_t *g_menubar = NULL;
static accel_table_t *g_accel = NULL;

// ══════════════════════════════════════════════════════════════════════════
// Feed List Management (AUTOMATIC via tableview!)
// ══════════════════════════════════════════════════════════════════════════

// No manual population needed - tableview handles everything automatically!

// ══════════════════════════════════════════════════════════════════════════
// New Post Dialog
// ══════════════════════════════════════════════════════════════════════════

static result_t new_post_proc(window_t *win, uint32_t msg, uint32_t wparam, void *lparam) {
  switch (msg) {
    case evCreate:
      // Populate author combobox from database
      {
        window_t *author_cb = get_window_item(win, ID_NEW_POST_AUTHOR);
        if (author_cb) {
          result_node_t *authors = (result_node_t *)send_db_message(g_db, dbFetch,
            MAKEDWORD(TABLE_AUTHORS, 0), (void *)(intptr_t)0);
          
          for (result_node_t *n = authors; n; n = (result_node_t *)n->next) {
            author_t *a = *(author_t **)n->data;
            send_message(author_cb, cbAddString, (uint32_t)(intptr_t)a->id, a->name);
          }
          
          free_result_list(authors);
          if (send_message(author_cb, cbGetCount, 0, NULL) > 0)
            send_message(author_cb, cbSetCurSel, 0, NULL);
        }
      }
      return true;
      
    case evCommand:
      if (HIWORD(wparam) == btnClicked) {
        window_t *src = (window_t *)lparam;
        
        // OK button: collect values and insert
        if (src->id == ID_NEW_POST_OK) {
          window_t *author_cb = get_window_item(win, ID_NEW_POST_AUTHOR);
          window_t *title_ed = get_window_item(win, ID_NEW_POST_TITLE);
          window_t *body_ed = get_window_item(win, ID_NEW_POST_BODY);
          
          if (!author_cb || !title_ed || !body_ed) {
            end_dialog(win, 0);
            return true;
          }
          
          // Get author_id from combobox
          int sel = (int)send_message(author_cb, cbGetCurSel, 0, NULL);
          if (sel < 0) {
            end_dialog(win, 0);
            return true;
          }
          intptr_t author_id = send_message(author_cb, cbGetItemData, (uint32_t)sel, NULL);
          
          // Get title and body text
          char title[256] = {0}, body[2048] = {0};
          get_window_text(title_ed, title, sizeof(title));
          get_window_text(body_ed, body, sizeof(body));
          
          if (title[0] == '\0') {
            end_dialog(win, 0);
            return true;
          }
          
          // Create post record
          post_t new_post = {
            .id = 0,
            .author_id = (int)author_id,
            .like_count = 0,
            .comment_count = 0
          };
          strncpy(new_post.title, title, sizeof(new_post.title) - 1);
          strncpy(new_post.body, body, sizeof(new_post.body) - 1);
          
          // Insert into database (Zero Wrapper Structs API!)
          post_t *inserted = (post_t *)send_db_message(g_db, dbInsert, TABLE_POSTS, &new_post);
          
          if (inserted) {
            // Refresh feed list via tableview
            window_t *feed = get_window_item(g_main_win, ID_MAIN_WINDOW_FEED);
            if (feed)
              send_message(feed, tvRefresh, 0, NULL);
            }
            end_dialog(win, 1);
          } else {
            end_dialog(win, 0);
          }
          return true;
        }
        
        // Cancel button
        if (src->id == ID_NEW_POST_CANCEL) {
          end_dialog(win, 0);
          return true;
        }
      }
      return false;
      
    default:
      return false;
  }
}

// ══════════════════════════════════════════════════════════════════════════
// Main Window Procedure
// ══════════════════════════════════════════════════════════════════════════

static result_t main_win_proc(window_t *win, uint32_t msg, uint32_t wparam, void *lparam) {
  switch (msg) {
    case evCreate: {
      // Replace form's reportview with tableview for automatic population
      window_t *old_feed = get_window_item(win, ID_MAIN_WINDOW_FEED);
      if (old_feed) {
        // Create tableview with same frame/parent but using database API
        tableview_params_t params = {
          .db = g_db,
          .table_id = TABLE_POSTS,
          .filter_field = 0,          // No filter (fetch all)
          .filter_value = 0,
          .field_names = (const char *[]){"title", "author", "like_count", "comment_count", NULL},
          .column_titles = (const char *[]){"Title", "Author", "Likes", "Comments", NULL},
          .column_widths = (const int[]){0, 80, 50, 50, -1}
        };
        
        // Create tableview in place of old reportview
        window_t *feed = create_window("", old_feed->flags, old_feed->frame,
                                       old_feed->parent, win_tableview, &params);
        if (feed) {
          feed->id = ID_MAIN_WINDOW_FEED;
          destroy_window(old_feed);
        }
      }
      return true;
    }
      
    case evCommand: {
      int cmd = LOWORD(wparam);
      
      switch (cmd) {
        case ID_FILE_QUIT:
          post_quit_message(0);
          return true;
          
        case ID_POST_NEW:
          show_dialog_from_form(&socialfeed_new_post_form, "New Post", win, new_post_proc, NULL);
          return true;
          
        case ID_VIEW_REFRESH: {
          // Send refresh message to tableview
          window_t *feed = get_window_item(win, ID_MAIN_WINDOW_FEED);
          if (feed)
            send_message(feed, tvRefresh, 0, NULL);
          }
          return true;
        }
          
        case ID_HELP_ABOUT:
          msgbox(win, "About Social Feed",
                 "Database-driven social feed using Zero Wrapper Structs API\n\n"
                 "Built with Orion UI framework",
                 MB_OK);
          return true;
      }
      return false;
    }
    
    case evClose:
      post_quit_message(0);
      return true;
      
    default:
      return false;
  }
}

// ══════════════════════════════════════════════════════════════════════════
// Application Lifecycle
// ══════════════════════════════════════════════════════════════════════════

bool gem_init(int argc, char *argv[], hinstance_t hinstance) {
  (void)argc; (void)argv; (void)hinstance;
  
  // Register database class
  DB_CLASS(db_simple_xml);
  
  // Create database instance (loads socialfeed_seed.xml automatically)
  char db_path[512];
  snprintf(db_path, sizeof(db_path), "%s/socialfeed_seed.xml", SHAREDIR);
  g_db = create_database("socialfeed", "db_simple_xml", db_path);
  if (!g_db) {
    fprintf(stderr, "Failed to create database\n");
    return false;
  }
  
  // Create menubar from generated definitions
  g_menubar = create_menubar(kMenus, kNumMenus);
  if (!g_menubar) {
    destroy_database(g_db);
    return false;
  }
  
  // Create main window from generated form
  g_main_win = create_window_from_form(&socialfeed_main_window_form,
    (ui_get_screen_width() - 472) / 2,
    (ui_get_screen_height() - 336) / 2,
    NULL, main_win_proc, NULL);
  
  if (!g_main_win) {
    destroy_database(g_db);
    return false;
  }
  
  // Add toolbar
  send_message(g_main_win, tbAddButtons, TB_FEED_COUNT, (void *)TB_FEED);
  
  // Show window
  show_window(g_main_win, true);
  
  return true;
}

void gem_shutdown(void) {
  if (g_db) {
    destroy_database(g_db);
    g_db = NULL;
  }
}

GEM_DEFINE("Social Feed (DB)", "1.0", gem_init, gem_shutdown, NULL)

GEM_STANDALONE_MAIN("Orion Social Feed", UI_INIT_DESKTOP, 800, 600, g_menubar, g_accel)
