// Simple test of database-driven dialog (manual bindings)
// This demonstrates the runtime infrastructure before automating code generation.

#include "../../ui.h"
#include "socialfeed.h"
#include <stdio.h>

// Manual binding example - will be auto-generated by orionc later
static const ctrl_binding_t author_bindings[] = {
  // ctrl_id, command, getter, offset, wparam, push, pull
  { 1, 0, edGetText, offsetof(db_author_t, name), sizeof(((db_author_t *)0)->name), NULL, NULL },
  { 2, 0, edGetText, offsetof(db_author_t, avatar), sizeof(((db_author_t *)0)->avatar), NULL, NULL },
};

// Manual form definition - will be generated by orionc later
static const form_ctrl_def_t author_edit_children[] = {
  { .class_name = "label", .id = 0, .size = {0, 13}, .flags = 0, .text = "Name:", .name = "lbl_name" },
  { .class_name = "textedit", .id = 1, .size = {0, 13}, .flags = WINDOW_FLEXSPACE, .text = "", .name = "edit_name" },
  { .class_name = "label", .id = 0, .size = {0, 13}, .flags = 0, .text = "Avatar:", .name = "lbl_avatar" },
  { .class_name = "textedit", .id = 2, .size = {0, 13}, .flags = WINDOW_FLEXSPACE, .text = "", .name = "edit_avatar" },
  { .class_name = "button", .id = 100, .size = {60, 19}, .flags = BUTTON_DEFAULT, .text = "OK", .name = "ok" },
  { .class_name = "button", .id = 101, .size = {60, 19}, .flags = 0, .text = "Cancel", .name = "cancel" },
};

static const form_def_t author_edit_form = {
  .name = "Edit Author",
  .width = 300,
  .height = 120,
  .flags = WINDOW_AUTO_LAYOUT,
  .layout_spacing = 8,
  .padding = {8, 8, 8, 8},
  .children = author_edit_children,
  .child_count = 6,
  .bindings = author_bindings,
  .binding_count = 2,
  .ok_id = 100,
  .cancel_id = 101,
  // Database metadata (would be auto-filled by orionc from field= attribute)
  .db_name = "db",
  .db_table = "authors",
  .db_table_id = TABLE_AUTHORS,
  .db_fields = (const void *)authors_fields,
  .db_field_count = 3,
};

// Test function - call from socialfeed to test
// NOTE: Database must be registered first via register_database("db", db)
void test_author_edit_dialog(window_t *parent, database_t *db) {
  printf("Testing database-driven author edit dialog...\n");
  
  // Register database instance (normally done once at startup)
  register_database("db", db);
  
  // NEW API: Form is self-contained - no db parameter needed!
  // The form knows db_name="db" from field="db.authors.name"
  uint32_t result = show_db_dialog(&author_edit_form, "Edit Author", parent, 1);
  
  if (result == 1) {
    printf("Author saved successfully!\n");
  } else {
    printf("Dialog cancelled.\n");
  }
}

// Test creating new author
void test_new_author_dialog(window_t *parent, database_t *db) {
  printf("Testing new author creation dialog...\n");
  
  // Register database instance
  register_database("db", db);
  
  // NEW API: Self-contained - form looks up database automatically
  uint32_t result = show_db_dialog(&author_edit_form, "New Author", parent, 0);
  
  if (result == 1) {
    printf("New author created!\n");
  } else {
    printf("Dialog cancelled.\n");
  }
}
