#include "../examples/formeditor/controls-icons.h"
#include "../ui.h"
#include "commctl.h"

static const fe_component_desc_t k_components[] = {
  {
    .class_name = "button",
    .display_name = "CommandButton",
    .token = "button",
    .name_prefix = "IDC_BTN",
    .toolbox_ident = 205,
    .toolbox_icon = IC_BUTTON,
    .default_size = {75, 23},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_button,
  },
  {
    .class_name = "checkbox",
    .display_name = "CheckBox",
    .token = "checkbox",
    .name_prefix = "IDC_CHK",
    .toolbox_ident = 206,
    .toolbox_icon = IC_CHECKBOX,
    .default_size = {97, 17},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_checkbox,
  },
  {
    .class_name = "label",
    .display_name = "Label",
    .token = "label",
    .name_prefix = "IDC_LBL",
    .toolbox_ident = 202,
    .toolbox_icon = IC_TEXT,
    .default_size = {65, 13},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_label,
  },
  {
    .class_name = "textedit",
    .display_name = "TextBox",
    .token = "textedit",
    .name_prefix = "IDC_EDT",
    .toolbox_ident = 203,
    .toolbox_icon = IC_TEXT_FIELD,
    .default_size = {121, 20},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_textedit,
  },
  {
    .class_name = "list",
    .display_name = "ListBox",
    .token = "list",
    .name_prefix = "IDC_LST",
    .toolbox_ident = 209,
    .toolbox_icon = IC_LIST_VIEW,
    .default_size = {121, 60},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_list,
  },
  {
    .class_name = "combobox",
    .display_name = "ComboBox",
    .token = "combobox",
    .name_prefix = "IDC_CMB",
    .toolbox_ident = 208,
    .toolbox_icon = IC_COMBO_BOX,
    .default_size = {121, 20},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_combobox,
  },
  {
    .class_name = "slider",
    .display_name = "Slider",
    .token = "slider",
    .name_prefix = "IDC_SLD",
    .toolbox_ident = 210,
    .toolbox_icon = IC_SLIDER,
    .default_size = {121, 17},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_slider,
  },
  {
    .class_name = "gradient",
    .display_name = "Gradient",
    .token = "gradient",
    .name_prefix = "IDC_GRD",
    .toolbox_ident = 211,
    .toolbox_icon = IC_PROGRESS_BAR,
    .default_size = {121, 8},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_gradient,
  },
  {
    .class_name = "column",
    .display_name = "Column",
    .token = "column",
    .name_prefix = "IDC_COL",
    .toolbox_ident = 213,
    .toolbox_icon = IC_PANEL,
    .default_size = {120, 80},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_column,
  },
  {
    .class_name = "flowview",
    .display_name = "FlowView",
    .token = "flow",
    .name_prefix = "IDC_FLOW",
    .toolbox_ident = 216,
    .toolbox_icon = IC_DOCUMENT_STACK,
    .default_size = {120, 80},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_flowview,
  },
  {
    .class_name = "reportview",
    .display_name = "ReportView",
    .token = "reportview",
    .name_prefix = "IDC_RVW",
    .toolbox_ident = 212,
    .toolbox_icon = IC_DETAILS_VIEW,
    .default_size = {160, 120},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_reportview,
  },
  {
    .class_name = "separator",
    .display_name = "Separator",
    .token = "separator",
    .name_prefix = "IDC_SEP",
    .toolbox_ident = 214,
    .toolbox_icon = IC_PANEL,
    .default_size = {80, 8},
    .capabilities = FE_COMPONENT_PLACEABLE | FE_COMPONENT_SHOW_TOOLBOX,
    .proc = win_separator,
  },
  {
    .class_name = "space",
    .display_name = "Space",
    .token = "space",
    .name_prefix = "IDC_SPC",
    .toolbox_ident = 215,
    .toolbox_icon = IC_PANEL,
    .default_size = {80, 40},
    .capabilities = FE_COMPONENT_PLACEABLE,
    .proc = win_space,
  },
};

GEM_CLASSES(k_components, "Orion built-in commctl components", FE_PLUGIN_VERSION)
