#ifndef __AICHAT_H__
#define __AICHAT_H__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>

#include "../../ui.h"
#include "../../commctl/columnview.h"
#include "../../commctl/menubar.h"
#include "../../user/accel.h"
#include "../../user/icons.h"

// All definitions generated from aichat.orion:
//   - Menu IDs, toolbar IDs, form definitions
//   - Database schema (table enums, structs, field bindings)
// NOTE: In a real build, this would be generated by orionc from aichat.orion
// For now, we manually define the necessary IDs and structs

// ============================================================
// Database Table IDs
// ============================================================

#define ID_DB_SESSIONS      1
#define ID_DB_MESSAGES      2

// Session field IDs
#define ID_DB_SESSIONS_ID           0
#define ID_DB_SESSIONS_TITLE        1
#define ID_DB_SESSIONS_CREATED_AT   2
#define ID_DB_SESSIONS_UPDATED_AT   3

// Message field IDs
#define ID_DB_MESSAGES_ID           0
#define ID_DB_MESSAGES_SESSION_ID   1
#define ID_DB_MESSAGES_ROLE         2
#define ID_DB_MESSAGES_CONTENT      3
#define ID_DB_MESSAGES_TIMESTAMP    4

// ============================================================
// Database Source IDs
// ============================================================

#define ID_DB_SOURCE_SESSIONS   10
#define ID_DB_SOURCE_MESSAGES   11
#define ID_DB_MODEL_SESSION     100
#define ID_DB_MODEL_MESSAGE     101

// ============================================================
// Database Action IDs
// ============================================================

#define ID_DB_ACTION_FETCH_SESSIONS     20
#define ID_DB_ACTION_FETCH_MESSAGES     21
#define ID_DB_ACTION_INSERT_SESSIONS    22
#define ID_DB_ACTION_INSERT_MESSAGES    23

// ============================================================
// Menu IDs
// ============================================================

#define ID_FILE_NEW_SESSION     1001
#define ID_FILE_SAVE_TRANSCRIPT 1002
#define ID_FILE_QUIT            1003

#define ID_SESSION_RENAME       1011
#define ID_SESSION_DELETE       1012
#define ID_SESSION_CLEAR        1013

#define ID_HELP_ABOUT           1021

// ============================================================
// Control IDs
// ============================================================

#define ID_MAIN_WINDOW_CONTENT      2001
#define ID_MAIN_WINDOW_SESSION_LIST 2002
#define ID_MAIN_WINDOW_MESSAGE_LIST 2003
#define ID_MAIN_WINDOW_USER_INPUT   2004
#define ID_MAIN_WINDOW_SEND         2005

#define ID_NEW_SESSION_TITLE        2101

// ============================================================
// Database Structs
// ============================================================

// Session record
typedef struct {
    int id;
    char title[128];
    char created_at[32];
    char updated_at[32];
} db_session_t;

// Message record
typedef struct {
    int id;
    int session_id;
    char role[16];
    char content[8192];
    char timestamp[32];
} db_message_t;

// ============================================================
// Field Metadata
// ============================================================

static const db_field_meta_t sessions_fields[] = {
    { ID_DB_SESSIONS_ID,         "id",         DB_TYPE_INT,    offsetof(db_session_t, id),         0 },
    { ID_DB_SESSIONS_TITLE,      "title",      DB_TYPE_STRING, offsetof(db_session_t, title),      sizeof(((db_session_t *)0)->title) },
    { ID_DB_SESSIONS_CREATED_AT, "created_at", DB_TYPE_STRING, offsetof(db_session_t, created_at), sizeof(((db_session_t *)0)->created_at) },
    { ID_DB_SESSIONS_UPDATED_AT, "updated_at", DB_TYPE_STRING, offsetof(db_session_t, updated_at), sizeof(((db_session_t *)0)->updated_at) },
};

static const db_field_meta_t messages_fields[] = {
    { ID_DB_MESSAGES_ID,         "id",         DB_TYPE_INT,    offsetof(db_message_t, id),         0 },
    { ID_DB_MESSAGES_SESSION_ID, "session_id", DB_TYPE_INT,    offsetof(db_message_t, session_id), 0 },
    { ID_DB_MESSAGES_ROLE,       "role",       DB_TYPE_STRING, offsetof(db_message_t, role),       sizeof(((db_message_t *)0)->role) },
    { ID_DB_MESSAGES_CONTENT,    "content",    DB_TYPE_STRING, offsetof(db_message_t, content),    sizeof(((db_message_t *)0)->content) },
    { ID_DB_MESSAGES_TIMESTAMP,  "timestamp",  DB_TYPE_STRING, offsetof(db_message_t, timestamp),  sizeof(((db_message_t *)0)->timestamp) },
};

// ============================================================
// Form Definitions (simplified - would be generated by orionc)
// ============================================================

// NOTE: In a real build, form definitions would be generated from .orion
// These are placeholder declarations

// ============================================================
// Database Implementation (db_simple_xml.c)
// ============================================================

lresult_t db_simple_xml(database_t *db, uint32_t msg, uint32_t wparam, void *lparam);

#ifndef AICHAT_DEBUG
#define AICHAT_DEBUG 1
#endif

#if AICHAT_DEBUG
#define AI_DEBUG(...) do { axLog("[aichat] " __VA_ARGS__); } while (0)
#else
#define AI_DEBUG(...) ((void)0)
#endif

// ============================================================
// Layout constants
// ============================================================

#define SCREEN_W  800
#define SCREEN_H  600

// ============================================================
// Application state
// ============================================================

typedef struct {
    database_t  *db;
    int          selected_session_idx;
    int          selected_message_idx;
    window_t    *menubar_win;
    window_t    *main_win;
    window_t    *session_list_win;
    window_t    *message_list_win;
    window_t    *user_input_win;
    hinstance_t  hinstance;
    accel_table_t *accel;
    
    // Current session
    int          current_session_id;
} app_state_t;

extern app_state_t *g_app;

// ============================================================
// Controller functions (controller_app.c)
// ============================================================

app_state_t *app_init(void);
void         app_shutdown(app_state_t *app);
bool         app_new_session(const char *title);
bool         app_delete_session(int session_id);
bool         app_rename_session(int session_id, const char *new_title);
void         app_select_session(int session_id);
bool         app_send_message(const char *content);
bool         app_save_transcript(const char *filepath);
void         app_update_status(void);

// ============================================================
// View — menu bar (view_menubar.c)
// ============================================================

void     handle_menu_command(uint16_t id);
lresult_t app_menubar_proc(window_t *win, uint32_t msg,
                          uint32_t wparam, void *lparam);
void     create_menubar(void);

// ============================================================
// View — main window (view_main.c)
// ============================================================

lresult_t main_win_proc(window_t *win, uint32_t msg,
                       uint32_t wparam, void *lparam);
void     session_list_refresh(void);
void     message_list_refresh(void);
void     create_main_window(void);

// ============================================================
// View — dialogs (view_dialogs.c)
// ============================================================

void show_new_session_dialog(window_t *parent);
void show_about_dialog(window_t *parent);

// ============================================================
// AI Integration (ai_agent.c)
// ============================================================

bool ai_send_message(const char *message, char *response, size_t response_size);

#endif // __AICHAT_H__