#ifndef __UI_DATABASE_H__
#define __UI_DATABASE_H__

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct database_s database_t;
typedef intptr_t lresult_t;  // Pointer-sized result (like WinAPI LRESULT)

// Database procedure callback type (analogous to winproc_t)
typedef lresult_t (*dbproc_t)(database_t *, uint32_t, uint32_t, void *);

// Database messages
enum {
  dbCreate,          // wparam=0; lparam=const char* source_path → returns 1 on success
  dbDestroy,         // cleanup → returns 1 on success
  dbLoad,            // load from source → returns 1 on success
  dbSave,            // save to source (only if dirty) → returns 1 on success
  dbInsert,          // wparam=table_id; lparam=record_data → returns (lresult_t)record_ptr
  dbUpdate,          // wparam=table_id; lparam=record_data → returns 1 on success
  dbDelete,          // wparam=table_id; lparam=(void*)(intptr_t)record_id → returns 1 on success
  dbFetch,           // wparam=MAKEDWORD(table_id,filter_field); lparam=(intptr_t)filter_value → returns (lresult_t)result_node_t* (linked list)
  dbFind,            // wparam=MAKEDWORD(table_id,search_field); lparam=(intptr_t)value or (void*)str → returns (lresult_t)record_ptr
  dbGetDirty,        // returns dirty flag as lresult_t (0 or 1)
  dbGetObjectProc,   // wparam=table_id; lparam=0 → returns (lresult_t)db_object_proc_t
  dbGetFieldBindings, // wparam=table_id; lparam=int* count_out → returns (lresult_t)db_field_msg_binding_t*
  dbGetTables,       // wparam=0; lparam=0 → returns (lresult_t)table_name_node_t* (linked list of table names)
  dbGetTableSchema,  // wparam=table_id; lparam=0 → returns (lresult_t)table_schema_t* (field metadata array)
  dbUser = 1000      // custom database implementations can use dbUser+
};

// Result node for dbFetch (linked list of records)
// Caller must free with free_result_list() after use
typedef struct result_node_s {
  void *next;              // Next node (NULL for last)
  char data[];             // Flexible array member - record data
} result_node_t;

// Table name node for dbGetTables (linked list of table names)
// Caller must free with free_result_list() after use
typedef struct table_name_node_s {
  struct table_name_node_s *next;  // Next node (NULL for last)
  char name[64];                   // Table name (e.g., "posts")
  int table_id;                    // Table ID for other messages
} table_name_node_t;

// Field types for reflection-based XML loading
typedef enum {
  DB_TYPE_INT,
  DB_TYPE_STRING,
  DB_TYPE_BOOL,
  DB_TYPE_FLOAT,
  DB_TYPE_DOUBLE
} db_field_type_t;

// Field metadata for reflection (generated by orionc from <table> schemas)
typedef struct {
  const char *name;        // Field name (e.g., "author_id")
  db_field_type_t type;    // C type
  size_t offset;           // offsetof(struct_t, field)
  int length;              // For strings: buffer size; else 0
} db_field_meta_t;

// Table schema for dbGetTableSchema (field metadata array)
// Returned pointer is owned by database - do NOT free
typedef struct {
  const db_field_meta_t *fields;   // Field metadata array
  int field_count;                 // Number of fields
} table_schema_t;

// Database class descriptor
typedef struct {
  const char *class_name;  // "SimpleXMLDatabase", etc.
  dbproc_t proc;           // database procedure
} db_class_desc_t;

// Database structure (analogous to window_t)
struct database_s {
  const char *name;        // database instance name
  const char *class_name;  // registered class name
  dbproc_t proc;           // database procedure
  void *userdata;          // implementation-specific data
  char source_path[512];   // path to XML/SQLite/etc. file
  bool dirty;              // needs save
};

// Database management functions
database_t *create_database(const char *name, const char *class_name, const char *source_path);
void destroy_database(database_t *db);
lresult_t send_db_message(database_t *db, uint32_t msg, uint32_t wparam, void *lparam);

// Result list helpers
void free_result_list(void *head);
int count_result_list(void *head);

// Reflection-based XML loading (uses generated field metadata from orionc)
// These helpers are available to all database implementations
#include <libxml/tree.h>
bool db_load_field_from_xml(xmlNodePtr node, void *record_base,
                             const db_field_meta_t *field);
bool db_load_record_from_xml(xmlNodePtr node, void *record,
                              const db_field_meta_t *fields, int field_count);

// Reflection-based XML saving (uses generated field metadata from orionc)
bool db_save_field_to_xml(xmlNodePtr node, const void *record_base,
                           const db_field_meta_t *field);
xmlNodePtr db_save_record_to_xml(xmlNodePtr parent, const char *element_name,
                                  const void *record, const db_field_meta_t *fields,
                                  int field_count);

// Database class registry
bool register_database_class(const db_class_desc_t *desc);
dbproc_t find_database_class_proc(const char *class_name);

// Database instance registry (for declarative forms)
// Forms with field="db.table.field" look up the database by name automatically
bool register_database(const char *name, database_t *db);
database_t *get_database_by_name(const char *name);

#define DB_CLASS(proc_sym) \
  register_database_class(&(db_class_desc_t){ .class_name = #proc_sym, .proc = (proc_sym) })

#endif // __UI_DATABASE_H__
