#ifndef __UI_DATABASE_H__
#define __UI_DATABASE_H__

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// Forward declarations
#ifndef UI_LRESULT_T_DEFINED
#define UI_LRESULT_T_DEFINED
typedef intptr_t lresult_t;
#endif

typedef struct database_s database_t;

// Database procedure callback type (analogous to winproc_t)
typedef lresult_t (*dbproc_t)(database_t *, uint32_t, uint32_t, void *);

// Database messages
enum {
  dbCreate,          // wparam=0; lparam=const char* source_path → returns 1 on success
  dbDestroy,         // cleanup → returns 1 on success
  dbLoad,            // load from source → returns 1 on success
  dbSave,            // save to source (only if dirty) → returns 1 on success
  dbInsert,          // wparam=table_id; lparam=record_data → returns (lresult_t)record_ptr
  dbUpdate,          // wparam=table_id; lparam=record_data → returns 1 on success
  dbDelete,          // wparam=table_id; lparam=(void*)(intptr_t)record_id → returns 1 on success
  dbFetch,           // wparam=MAKEDWORD(table_id,filter_field); lparam=(intptr_t)filter_value → returns (lresult_t)result_node_t* (linked list)
  dbFind,            // wparam=MAKEDWORD(table_id,search_field); lparam=(intptr_t)value or (void*)str → returns (lresult_t)record_ptr
  dbGetDirty,        // returns dirty flag as lresult_t (0 or 1)
  dbGetObjectProc,   // wparam=table_id; lparam=0 → returns (lresult_t)db_object_proc_t
  dbGetFieldBindings, // wparam=table_id; lparam=int* count_out → returns (lresult_t)db_field_msg_binding_t*
  dbGetSchema,       // wparam=0; lparam=0 → returns (lresult_t)const db_schema_def_t*
  dbGetApi,          // wparam=0; lparam=0 → returns (lresult_t)const db_api_def_t*
  dbUser = 1000      // custom database implementations can use dbUser+
};

// Result node for dbFetch (linked list of records)
// Caller must free with free_result_list() after use
typedef struct result_node_s {
  void *next;              // Next node (NULL for last)
  char data[];             // Flexible array member - record data
} result_node_t;

// Field types for reflection-based XML loading
typedef enum {
  DB_TYPE_INT,
  DB_TYPE_STRING,
  DB_TYPE_BOOL,
  DB_TYPE_FLOAT,
  DB_TYPE_DOUBLE
} db_field_type_t;

// Field metadata for reflection (generated by orionc from <table> schemas)
typedef struct {
  const char *name;        // Field name (e.g., "author_id")
  db_field_type_t type;    // C type
  size_t offset;           // offsetof(struct_t, field)
  int length;              // For strings: buffer size; else 0
} db_field_meta_t;

// Design-time schema metadata for editor/database browsers.
typedef struct {
  const char *name;            // Field name (e.g., "author_id")
  db_field_type_t type;        // Field type
  int length;                  // String buffer size; else 0
  bool primary_key;            // true for key fields
  const char *relation_table;  // Foreign table, if this field references one
  const char *relation_field;  // Foreign field, if this field references one
} db_field_schema_t;

typedef struct {
  const char *name;          // Join alias (e.g., "author")
  const char *local_field;   // Local FK field (e.g., "author_id")
  const char *foreign_table; // Referenced table (e.g., "authors")
  const char *foreign_field; // Referenced field (e.g., "id")
} db_join_schema_t;

typedef struct {
  int table_id;                         // TABLE_* value
  const char *name;                     // Table name (e.g., "posts")
  const char *model;                    // Optional logical model name
  const db_field_schema_t *fields;
  int field_count;
  const db_join_schema_t *joins;
  int join_count;
} db_table_schema_t;

typedef struct {
  const char *name;                     // Database instance name
  const char *class_name;               // Database class/proc name
  const char *source_path;              // Backing source, if any
  const db_table_schema_t *tables;
  int table_count;
} db_schema_def_t;

// Declarative database API metadata emitted from .orion documents.
// This metadata is model/view-agnostic and can be consumed by applications to
// drive fetch actions and view bindings without hard-coded column setup.
typedef struct {
  const char *name;   // source name, e.g. "feed_posts"
  const char *model;  // logical model name, e.g. "post"
} db_source_def_t;

typedef struct {
  const char *field;  // model field key, e.g. "title"
  const char *title;  // view column title
  int         width;  // preferred column width; <=0 means auto/flex
} db_binding_column_t;

typedef struct {
  const char                *name;   // binding identifier
  const char                *source; // source name this binding reads from
  const char                *view;   // target view/control name
  const db_binding_column_t *columns;
  int                        column_count;
} db_view_binding_t;

typedef enum {
  DB_ACTION_FETCH = 1,
  DB_ACTION_INSERT,
  DB_ACTION_UPDATE,
  DB_ACTION_DELETE,
  DB_ACTION_CUSTOM,
} db_action_kind_t;

typedef struct {
  const char       *name;   // action identifier
  db_action_kind_t  kind;   // fetch/insert/update/delete/custom
  const char       *source; // source name this action targets
  const char       *target; // target view/control or route name
} db_action_def_t;

typedef struct {
  const char *name;   // outlet identifier
  const char *type;   // expected object/control type, if known
  const char *target; // connected view/control name, if known
} db_outlet_def_t;

typedef struct {
  const db_source_def_t   *sources;
  int                      source_count;
  const db_view_binding_t *bindings;
  int                      binding_count;
  const db_action_def_t   *actions;
  int                      action_count;
  const db_outlet_def_t   *outlets;
  int                      outlet_count;
} db_api_def_t;

typedef lresult_t (*db_object_proc_t)(const void *object, uint32_t msg,
                                      uint32_t wparam, void *lparam);

// Action verbs for database object handlers (Action-Message DDX pattern).
// msg carries the verb; wparam carries packed payload metadata.
typedef enum {
  dbObjGetFieldText = 1,
  dbObjSetFieldText,
} db_object_action_t;

// Field-to-column lookup used by db_object_get_field_text().
// The mapped column_id is packed into LOWORD(wparam).
typedef struct {
  const char *field;
  uint16_t    column_id;
} db_field_msg_binding_t;

// Database class descriptor
typedef struct {
  const char *class_name;  // "SimpleXMLDatabase", etc.
  dbproc_t proc;           // database procedure
} db_class_desc_t;

// Database structure (analogous to window_t)
struct database_s {
  const char *name;        // database instance name
  const char *class_name;  // registered class name
  dbproc_t proc;           // database procedure
  void *userdata;          // implementation-specific data
  char source_path[512];   // path to XML/SQLite/etc. file
  bool dirty;              // needs save
};

// Database management functions
database_t *create_database(const char *name, const char *class_name, const char *source_path);
void destroy_database(database_t *db);
lresult_t send_db_message(database_t *db, uint32_t msg, uint32_t wparam, void *lparam);

// Declarative database API helpers
const db_source_def_t  *db_api_find_source(const db_api_def_t *api, const char *name);
const db_view_binding_t *db_api_find_binding(const db_api_def_t *api, const char *name);
const db_view_binding_t *db_api_find_binding_for_view(const db_api_def_t *api, const char *view);
const db_action_def_t  *db_api_find_action(const db_api_def_t *api, const char *name);
const db_outlet_def_t  *db_api_find_outlet(const db_api_def_t *api, const char *name);
bool db_object_get_field_text(const db_field_msg_binding_t *bindings, int binding_count,
                              db_object_proc_t proc, const void *object,
                              const char *field, char *buf, size_t buf_sz);

// Result list helpers
void free_result_list(void *head);
int count_result_list(void *head);

// Reflection-based XML loading (uses generated field metadata from orionc)
// These helpers are available to all database implementations
#include <libxml/tree.h>
bool db_load_field_from_xml(xmlNodePtr node, void *record_base,
                             const db_field_meta_t *field);
bool db_load_record_from_xml(xmlNodePtr node, void *record,
                              const db_field_meta_t *fields, int field_count);

// Reflection-based XML saving (uses generated field metadata from orionc)
bool db_save_field_to_xml(xmlNodePtr node, const void *record_base,
                           const db_field_meta_t *field);
xmlNodePtr db_save_record_to_xml(xmlNodePtr parent, const char *element_name,
                                  const void *record, const db_field_meta_t *fields,
                                  int field_count);

// Database class registry
bool register_database_class(const db_class_desc_t *desc);
dbproc_t find_database_class_proc(const char *class_name);

// Database instance registry (for declarative forms)
// Forms with field="db.table.field" look up the database by name automatically
bool register_database(const char *name, database_t *db);
database_t *get_database_by_name(const char *name);

#define DB_CLASS(proc_sym) \
  register_database_class(&(db_class_desc_t){ .class_name = #proc_sym, .proc = (proc_sym) })

#endif // __UI_DATABASE_H__
