#ifndef __UI_DATABASE_H__
#define __UI_DATABASE_H__

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// Forward declarations
#ifndef UI_LRESULT_T_DEFINED
#define UI_LRESULT_T_DEFINED
typedef intptr_t lresult_t;
#endif

typedef struct database_s database_t;

// Database procedure callback type (analogous to winproc_t)
typedef lresult_t (*dbproc_t)(database_t *, uint32_t, uint32_t, void *);

// Database messages
enum {
  dbCreate,          // wparam=0; lparam=const char* source_path → returns 1 on success
  dbDestroy,         // cleanup → returns 1 on success
  dbLoad,            // load from source → returns 1 on success
  dbSave,            // save to source (only if dirty) → returns 1 on success
  dbInsert,          // wparam=table_id; lparam=record_data → returns (lresult_t)record_ptr
  dbUpdate,          // wparam=table_id; lparam=record_data → returns 1 on success
  dbDelete,          // wparam=table_id; lparam=(void*)(intptr_t)record_id → returns 1 on success
  dbFetch,           // wparam=MAKEDWORD(table_id,filter_field); lparam=(intptr_t)filter_value → returns (lresult_t)result_node_t* (linked list)
  dbFind,            // wparam=MAKEDWORD(table_id,search_field); lparam=(intptr_t)value or (void*)str → returns (lresult_t)record_ptr
  dbGetDirty,        // returns dirty flag as lresult_t (0 or 1)
  dbGetSchema,       // wparam=0; lparam=0 → returns (lresult_t)const db_schema_def_t*
  dbGetFieldMeta,    // wparam=table_id; lparam=int* count_out → returns (lresult_t)const db_field_meta_t*
  dbGetApi,          // wparam=0; lparam=0 → returns (lresult_t)const db_api_def_t*
  dbUser = 1000      // custom database implementations can use dbUser+
};

// Result node for dbFetch (linked list of records)
// Caller must free with free_result_list() after use
typedef struct result_node_s {
  void *next;              // Next node (NULL for last)
  char data[];             // Flexible array member - record data
} result_node_t;

// Field types for reflection-based XML loading
typedef enum {
  DB_TYPE_INT,
  DB_TYPE_STRING,
  DB_TYPE_BOOL,
  DB_TYPE_FLOAT,
  DB_TYPE_DOUBLE
} db_field_type_t;

// Field metadata for reflection (generated by orionc from <table> schemas)
typedef struct {
  uint32_t field_id;        // Generated ID_DB_* field id
  const char *name;        // Field name (e.g., "author_id")
  db_field_type_t type;    // C type
  size_t offset;           // offsetof(struct_t, field)
  int length;              // For strings: buffer size; else 0
} db_field_meta_t;

// Design-time schema metadata for editor/database browsers.
typedef struct {
  uint32_t field_id;         // Generated ID_DB_* field id
  const char *name;            // Field name (e.g., "author_id")
  db_field_type_t type;        // Field type
  int length;                  // String buffer size; else 0
  bool primary_key;            // true for key fields
  uint32_t relation_table_id;  // Foreign table id, if this field references one
  uint32_t relation_field_id;  // Foreign field id, if this field references one
  bool relation_many;          // true for inverse/collection relationships
} db_field_schema_t;

typedef struct {
  uint32_t join_id;          // Generated ID_DB_* join id/alias id
  const char *name;          // Join alias (e.g., "author")
  uint32_t local_field_id;   // Local FK field id (e.g., author_id)
  uint32_t foreign_table_id; // Referenced table id (e.g., authors)
  uint32_t foreign_field_id; // Referenced field id (e.g., id)
} db_join_schema_t;

typedef struct {
  uint32_t table_id;                    // TABLE_* / ID_DB_* table id
  const char *name;                     // Table name (e.g., "posts")
  uint32_t model_id;                    // Generated model id
  const char *model;                    // Optional logical model name
  const db_field_schema_t *fields;
  int field_count;
  const db_join_schema_t *joins;
  int join_count;
} db_table_schema_t;

typedef struct {
  const char *name;                     // Database instance name
  const char *class_name;               // Database class/proc name
  const char *source_path;              // Backing source, if any
  const db_table_schema_t *tables;
  int table_count;
} db_schema_def_t;

// Declarative database API metadata emitted from .orion documents.
// This metadata is model/view-agnostic and can be consumed by applications to
// drive fetch actions and view bindings without hard-coded column setup.
typedef struct {
  uint32_t source_id;  // generated source id
  uint32_t model_id;   // generated model id
} db_source_def_t;

typedef struct {
  uint32_t    field_id; // model field id, e.g. ID_DB_*_POSTS_TITLE
  const char *title;  // view column title
  int         width;  // preferred column width; <=0 means auto/flex
} db_binding_column_t;

typedef struct {
  uint32_t                   binding_id; // binding identifier
  uint32_t                   source_id;  // source id this binding reads from
  uint32_t                   view_id;    // target view/control id
  const db_binding_column_t *columns;
  int                        column_count;
} db_view_binding_t;

typedef enum {
  DB_ACTION_FETCH = 1,
  DB_ACTION_INSERT,
  DB_ACTION_UPDATE,
  DB_ACTION_DELETE,
  DB_ACTION_CUSTOM,
} db_action_kind_t;

typedef struct {
  uint32_t          action_id; // action identifier
  db_action_kind_t  kind;   // fetch/insert/update/delete/custom
  uint32_t          source_id; // source id this action targets
  uint32_t          target_id; // target view/control or route id
} db_action_def_t;

typedef struct {
  uint32_t outlet_id; // outlet identifier
  uint32_t type_id;   // expected object/control type id, if known
  uint32_t target_id; // connected view/control id, if known
} db_outlet_def_t;

typedef struct {
  const db_source_def_t   *sources;
  int                      source_count;
  const db_view_binding_t *bindings;
  int                      binding_count;
  const db_action_def_t   *actions;
  int                      action_count;
  const db_outlet_def_t   *outlets;
  int                      outlet_count;
} db_api_def_t;

// Database class descriptor
typedef struct {
  const char *class_name;  // "SimpleXMLDatabase", etc.
  dbproc_t proc;           // database procedure
} db_class_desc_t;

// Database structure (analogous to window_t)
struct database_s {
  const char *name;        // database instance name
  const char *class_name;  // registered class name
  dbproc_t proc;           // database procedure
  void *userdata;          // implementation-specific data
  char source_path[512];   // path to XML/SQLite/etc. file
  bool dirty;              // needs save
};

// Database management functions
database_t *create_database(const char *name, const char *class_name, const char *source_path);
void destroy_database(database_t *db);
lresult_t send_db_message(database_t *db, uint32_t msg, uint32_t wparam, void *lparam);

// Declarative database API helpers
const db_source_def_t  *db_api_find_source(const db_api_def_t *api, uint32_t source_id);
const db_view_binding_t *db_api_find_binding(const db_api_def_t *api, uint32_t binding_id);
const db_view_binding_t *db_api_find_binding_for_view(const db_api_def_t *api, uint32_t view_id);
const db_action_def_t  *db_api_find_action(const db_api_def_t *api, uint32_t action_id);
const db_outlet_def_t  *db_api_find_outlet(const db_api_def_t *api, uint32_t outlet_id);
const db_table_schema_t *db_schema_find_table_by_id(const db_schema_def_t *schema, uint32_t table_id);
const db_table_schema_t *db_schema_find_table_by_name(const db_schema_def_t *schema, const char *name);
const db_field_schema_t *db_table_find_field_by_id(const db_table_schema_t *table, uint32_t field_id);
const db_field_schema_t *db_table_find_field_by_name(const db_table_schema_t *table, const char *name);
bool db_schema_resolve_many_relationship(const db_schema_def_t *schema,
                                         const db_table_schema_t *master_table,
                                         const char *relation_name,
                                         const db_table_schema_t **detail_table_out,
                                         const db_field_schema_t **filter_field_out);
bool db_get_schema_field_text(database_t *db, uint32_t table_id, const void *record,
                              uint32_t field_id, char *buf, size_t buf_sz);

// Result list helpers
void free_result_list(void *head);
int count_result_list(void *head);

// Reflection-based XML loading (uses generated field metadata from orionc)
// These helpers are available to all database implementations
#include <libxml/tree.h>
bool db_load_field_from_xml(xmlNodePtr node, void *record_base,
                             const db_field_meta_t *field);
bool db_load_record_from_xml(xmlNodePtr node, void *record,
                              const db_field_meta_t *fields, int field_count);

// Reflection-based XML saving (uses generated field metadata from orionc)
bool db_save_field_to_xml(xmlNodePtr node, const void *record_base,
                           const db_field_meta_t *field);
xmlNodePtr db_save_record_to_xml(xmlNodePtr parent, const char *element_name,
                                  const void *record, const db_field_meta_t *fields,
                                  int field_count);

// Database class registry
bool register_database_class(const db_class_desc_t *desc);
dbproc_t find_database_class_proc(const char *class_name);

// Database instance registry (for declarative forms)
// Forms with field="db.table.field" look up the database by name automatically
bool register_database(const char *name, database_t *db);
database_t *get_database_by_name(const char *name);

#define DB_CLASS(proc_sym) \
  register_database_class(&(db_class_desc_t){ .class_name = #proc_sym, .proc = (proc_sym) })

#endif // __UI_DATABASE_H__
